project:
  type: book
  output-dir: docs

book:
  title: "Exploring Modeling with Data and Differential Equations Using R"
  output-file: "modeling-2025"
  author: "John Zobitz"
  date: "June 3, 2025"

  chapters:
    - index.qmd
    - part: p01-models.qmd
      chapters:
      - 01-intro.qmd
      - 02-Rintro.qmd
      - 03-modelingWithRates.qmd
      - 04-eulersmethod.qmd
      - 05-phase.qmd
    - references.qmd

bibliography: book.bib

execute:
  freeze: auto
  echo: true
  warning: false
  message: false

  
format:
  html:
    theme: cosmo
