project:
  type: book
  output-dir: docs


book:
  title: "Exploring Modeling with Data and Differential Equations Using R"
  output-file: "modeling-2025"
  author: "John Zobitz"
  date: "August 2025"

  chapters:
    - index.qmd
    - part: p01-models.qmd
      chapters:
        - 01-intro.qmd
        - 02-Rintro.qmd
        - 03-modelingWithRates.qmd
        - 04-eulersmethod.qmd
        - 05-phase.qmd
        - 06-coupledSystems.qmd
        - 07-exactSolutions.qmd
    - part: p02-parameter.qmd
      chapters:
        - 08-linearRegression.qmd
        - 09-likelihood.qmd
        - 10-costFunctions.qmd
        - 11-bootstrap.qmd
        - 12-metropolis.qmd
        - 13-mcmc.qmd
        - 14-informationCriteria.qmd
    - part: p03-stability.qmd
      chapters:
        - 15-linearSystems.qmd
        - 16-nonlinearSystems.qmd
        - 17-jacobian.qmd
        - 18-eigenvalues.qmd
        - 19-qualitativeStability.qmd
        - 20-bifurcation.qmd
    - part: p04-stochastic.qmd
      chapters:
        - 21-stochasticSystems.qmd
        - 22-stochasticSimulation.qmd
        - 23-randomWalks.qmd
        - 24-diffusion.qmd
        - 25-sdes.qmd
        - 26-birthDeath.qmd
        - 27-solvingSDEs.qmd 
    - references.qmd

bibliography: book.bib

execute:
  freeze: auto
  echo: true
  warning: false
  message: false

  
format:
  html:
    theme:
      light: cosmo
      dark: darkly