{
  "hash": "74a4001f929e38b1d8f0a4fd58b5d34a",
  "result": {
    "engine": "knitr",
    "markdown": "# Probability and Likelihood Functions {#sec-likelihood-09}\n\nIn @sec-linear-regression-08 we began to the process of parameter estimation. We revisit parameter estimation here by applying _likelihood functions_, which is a topic from probability and statistics.\\index{likelihood!function} Probability is the association of a set of observable events to a quantitative scale between 0 and 1. Informally, a value of zero means that event is not possible; 1 means that it definitely can happen.^[See @devore_modern_2021 for a more refined definition of probability.] We will only consider continuous events with the range of parameter estimation problems examined here. \n\nThis chapter will introduce likelihood functions but also discuss some interesting visualization techniques of multivariable functions and contour plots. As with @sec-linear-regression-08 we are starting to build out some `R` skills and techniques that you can apply in other contexts. Let's get started!\n\n::: {.callout-note}\nThis chapter uses following libraries: `ggplot2`, and `tibble` (all part of the `tidyverse`) and `demodelr`. See @sec-packages-02 on how to install packages.  Prior to running any code in this section, include `library(tidyverse)` and `library(demodelr)`. \n:::\n\n\n## Linear regression on a small dataset\n@tbl-limited-data-09 displays a dataset with a limited number of points where we wish to fit the function $y=bx$:\n\n::: {#tbl-limited-data-09}\n\n| *x* | 1 | 2 | 4 | 4 | \n|:------:|:-----:|:-----:|:-----:|:-----:|\n| *y* | 3 | 5 | 4 | 10 |\n\nA small, limited dataset.\n:::\n\nFor this example we are forcing the intercept term to equal zero - for most cases you will just fit the linear equation (see @exr-full-linear where you will consider the intercept $a$). @fig-quick-scatter-09 displays a quick scatterplot of these data:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![A scatterplot of a small, limited dataset (@tbl-limited-data-09).](09-likelihood_files/figure-html/fig-quick-scatter-09-1.png){#fig-quick-scatter-09 width=672}\n:::\n:::\n\n\nThe goal here is to work to determine the value of $b$ that is most *likely* - or consistent - with the data. However, before we tackle this further we need to understand how to quantify most _likely_ in a mathematical sense. In order to do this, we need to take a quick excursion into continuous probability distributions.\n\n## Continuous probability density functions\nConsider @fig-normal-shaded-09, which may be familiar to you as the normal distribution or the bell curve:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The standard normal distribution, with a shaded area between $x=\\pm 1$](09-likelihood_files/figure-html/fig-normal-shaded-09-1.png){#fig-normal-shaded-09 width=672}\n:::\n:::\n\n\n\nWe tend to think of the plot and the associated function $f(x)$ as something with input and output (such as $f(0)=$ 0.3989). However because it is a probability density function, the *area* between two points yields the probability of an event to fall within two values as shown in @fig-normal-shaded-09.\n\n\nIn this case, the numerical value of the shaded area would represent the probability that our measurement is in the interval $-1 \\leq x \\leq 1$. The value of the area, or the probability, is 0.68269. Perhaps when you studied calculus the area was expressed as a definite integral:  $\\displaystyle \\int_{-1}^{1} f(x) \\; dx=$ 0.68269, where $f(x)$ is the formula for the probability density function for the normal distribution. Here, the formula for the normal distribution $f(x)$ is given by @eq-normal-09, where $\\mu$ is the mean and $\\sigma$ is the standard deviation.^[Were you ever asked to find the antiderivative of $\\displaystyle \\int e^{-x^{2}} \\; dx$? You may recall that there is easy antiderivative - and to find values of definite integrals you need to approximate numerically. Thankfully `R` does that work using sophisticated numerical integration techniques!]\n\n$$\nf(x)=\\frac{1}{\\sqrt{2 \\pi} \\sigma } e^{-(x-\\mu)^{2}/(2 \\sigma^{2})}\n$$ {#eq-normal-09}\n\n\n\nWith this intuition we can summarize key facts about probability density functions:\n\n- $f(x) \\geq 0$ (this means that probability density functions are positive values)\n- Area integrates to one (in probability, this means we have accounted for all of our outcomes)\n\n\n## Connecting probabilities to linear regression\nNow that we have made that small excursion into probability, let's return to the parameter estimation problem. Another way to phrase this problem is to examine the probability distribution of the model-data residual\\index{residual!model-data} for each measurement $\\epsilon_{i}$ (@eq-model-data-resid-09):\n\n$$\n\\epsilon_{i} = y_{i} - f(x_{i},\\vec{\\alpha} ).\n$$  {#eq-model-data-resid-09}\n\nThe approach with likelihood functions assumes a particular probability distribution on each residual. One common assumption is that the model-data residual is normally distributed. In most applications the mean of this distribution is zero ($\\mu=0$) and the standard deviation $\\sigma$ (which could be specified as measurement error, etc.). We formalize this assumption with a likelihood function $L$ in @eq-likelihood-resid-09.\n\n$$\nL(\\epsilon_{i}) = \\frac{1}{\\sqrt{2 \\pi} \\sigma} e^{-\\epsilon_{i}^{2} / 2 \\sigma^{2} } \n$$ {#eq-likelihood-resid-09}\n\nTo extend this further across all measurements, we use the idea of *independent, identically distributed* measurements so the joint likelihood of **all** the residuals (each $\\epsilon_{i}$) is the product of the individual likelihoods (@eq-likelihood-prod-09. The assumption of independent, identically distributed is a common one. As a note of caution you should always evaluate if this is a valid assumption for more advanced applications.\n\n$$\nL(\\vec{\\epsilon}) = \\prod_{i=1}^{N} \\frac{1}{\\sqrt{2 \\pi} \\sigma} e^{-\\epsilon_{i}^{2} / 2 \\sigma^{2} } \n$$ {#eq-likelihood-prod-09}\n\n\n\nWe are making progress here; however to fully characterize the solution we need to specify the parameters $\\vec{\\alpha}$. A simple redefining of the likelihood function where we specify the measurements ($x$ and $y$) and parameters ($\\vec{\\alpha}$) is all we need (@eq-likelihood-prod-param-09).\n\n$$\nL(\\vec{\\alpha} | \\vec{x},\\vec{y} )= \\prod_{i=1}^{N}  \\frac{1}{\\sqrt{2 \\pi} \\sigma} \\exp(-(y_{i} - f(x_{i},\\vec{\\alpha} ))^{2} / 2 \\sigma^{2} )\n$$ {#eq-likelihood-prod-param-09}\n\nNow with @eq-likelihood-prod-param-09 we have a function where the best parameter estimate is the one that optimizes the likelihood.\n\nReturning to our original linear regression problem (@tbl-limited-data-09 and @fig-quick-scatter-09), we want to determine the $b$ for the function $y=bx$. @eq-small-data-likely then characterizes the likelihood of $b$, given the data $\\vec{x}$ and $\\vec{y}$:\n\n$$\nL(b | \\vec{x},\\vec{y} ) = \\left( \\frac{1}{\\sqrt{2 \\pi} \\sigma}\\right)^{4} e^{-\\frac{(3-b)^{2}}{2\\sigma^{2}}} \\cdot e^{-\\frac{(5-2b)^{2}}{2\\sigma^{2}}}  \\cdot e^{-\\frac{(4-4b)^{2}}{2\\sigma^{2}}}  \\cdot e^{-\\frac{(10-4b)^{2}}{2\\sigma^{2}}}\n$$  {#eq-small-data-likely}\n\nFor the purposes of our argument here, we will assume $\\sigma=1$. @fig-small-likelihood-plot shows a plot of the likelihood function $L(b | \\vec{x},\\vec{y} )$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The likelihood function (@eq-small-data-likely) for the small dataset (@tbl-limited-data-09), with the value of the maximum likelihood at $b=1.865$ marked with a vertical line.](09-likelihood_files/figure-html/fig-small-likelihood-plot-1.png){#fig-small-likelihood-plot width=672}\n:::\n:::\n\n\n\nNote that in @fig-small-likelihood-plot the values of $L(b | \\vec{x},\\vec{y} )$ on the vertical axis are really small. (This typically may be the case; see Exercise \\@ref(exr:show-small-likely).) An alternative to the small numbers in $L(b)$ is to use the log-likelihood (@eq-loglikely):\n\n$$\n\\begin{split}\n\\ln(L(\\vec{\\alpha} | \\vec{x},\\vec{y} )) &=  N \\ln \\left( \\frac{1}{\\sqrt{2 \\pi} \\sigma} \\right) - \\sum_{i=1}^{N} \\frac{ (y_{i} - f(x_{i},\\vec{\\alpha} )^{2}}{ 2 \\sigma^{2}} \\\\\n & = - \\frac{N}{2} \\ln (2) - \\frac{N}{2} \\ln(\\pi) - N \\ln( \\sigma) - \\sum_{i=1}^{N} \\frac{ (y_{i} - f(x_{i},\\vec{\\alpha} )^{2}}{ 2 \\sigma^{2}}\n\\end{split}\n$$ {#eq-loglikely}\n\nIn @exr-small-data-optimize) you will be working on how to transform the likelihood function $L(b)$ to the log-likelihood $\\ln(L(b))$ and showing that @eq-small-data-likely is maximized at $b=1.865$. The data with the fitted line is shown in @fig-quick-scatter-fit-09.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![A scatterplot of a small dataset (@tbl-limited-data-09) with fitted line $y=1.865x$ from optimizing @eq-small-data-likely.](09-likelihood_files/figure-html/fig-quick-scatter-fit-09-1.png){#fig-quick-scatter-fit-09 width=672}\n:::\n:::\n\n\n\n\n## Visualizing likelihood surfaces\nNext we are going to examine a second example from @gause_experimental_1932 which modeled the growing of yeast in solution. This classic paper examines the biological principal of *competitive exclusion*, how one species can out-compete another one for resources. Some of the data from @gause_experimental_1932 is encoded in the data frame `yeast` in the `demodelr` package. For this example we are going to examine a model for one species growing without competition. @fig-yeast-quick-09 shows a scatterplot of the `yeast` data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Make a quick ggplot of the data\n\nggplot() +\n  geom_point(\n    data = yeast,\n    aes(x = time, y = volume),\n    color = \"red\",\n    size = 2\n  ) +\n  labs(x = \"Time\", y = \"Volume\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Scatterplot of *Sacchromyces* volume growing by itself in a container.](09-likelihood_files/figure-html/fig-yeast-quick-09-1.png){#fig-yeast-quick-09 width=672}\n:::\n:::\n\n\n\nWe are going to assume the population of yeast (represented with the measurement of volume) over time changes according to the differential equation $\\displaystyle \\frac{dy}{dt} = -by \\frac{(K-y)}{K}$, where $y$ is the population of the yeast, and $b$ represents the growth rate, and $K$ is the carrying capacity of the population. \n\n@eq-gause-09 shows the solution to this differential equation, where the additional parameter $a$ can be found through application of the initial condition $y_{0}$. \n\n$$\ny = \\frac{K}{1+e^{a-bt}}\n$$ {#eq-gause-09}\n\nIn @gause_experimental_1932 the value of $a$ was determined by solving the initial value problem $y(0)=0.45$. In Exercise \\@ref(exr:solve-gause) you will show that $\\displaystyle a = \\ln \\left( \\frac{K}{0.45} - 1 \\right)$. @eq-gause-09 then has two parameters: $K$ and $b$. Here we are going to explore the likelihood function to try to determine the best set of values for the two parameters $K$ and $b$ using a function in the `demodelr` package called `compute_likelihood`. Inputs to the `compute_likelihood` function are the following:\n\n- A function $y=f(x,\\vec{\\alpha})$\n- A dataset $(\\vec{x},\\vec{y})$\n- Ranges of your parameters $\\vec{\\alpha}$. \n\nThe `compute_likelihood` function also has an optional input `logLikely` that allows you to specify if you want to compute the likelihood or the log-likelihood. The default is that `logLikely` is `FALSE`, meaning that the normal likelihoods are plotted.\\index{likelihood!surface}\n\n\nFirst we will define the equation used to compute our model in the likelihood. As with the functions `euler` or `systems` in @sec-euler-04 we need to define this function:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(demodelr)\n\n# Define the solution to the differential equation with\n# parameters K and bGause model equation\ngause_model <- volume ~ K / (1 + exp(log(K / 0.45 - 1) - b * time))\n\n\n# Identify the ranges of the parameters that we wish to investigate\nkParam <- seq(5, 20, length.out = 100)\nbParam <- seq(0, 1, length.out = 100)\n\n\n# Allow for all the possible combinations of parameters\ngause_parameters <- expand.grid(K = kParam, b = bParam)\n\n# Now compute the likelihood\ngause_likelihood <- compute_likelihood(\n  model = gause_model,\n  data = yeast,\n  parameters = gause_parameters,\n  logLikely = FALSE\n  )\n```\n:::\n\n\nOk, let's break this code down step by step:\n\n- The line `gause_model <- volume ~ K/(1+exp(log(k/0.45-1)-b*time))` identifies the formula that relates the variables `time` to `volume` in the dataset `yeast`.\n- We define the ranges (minimum and maximum values) for our parameters by defining a sequence. Because we want to look at *all possible combinations* of these parameters we use the command `expand.grid`.\n- The input `logLikely = FALSE` to `compute_likelihood` reports back likelihood values.\n\nSome care is needed in defining the number of points (`length.out = 100`) in the sequence that we want to evaluate - we will have $100^{2}$ different combinations of $K$ and $b$ on our grid, which does take time to evaluate.\n\n\nThe output to `compute_likelihood` is a list, which is a flexible data structure in `R`. You can think of this as a collection of items - which could be data frames of different sizes. In this case, what gets returned are two data frames: `likelihood`, which is a data frame of likelihood values for each of the parameters and `opt_value`, which reports back the values of the parameters that optimize the likelihood function. Note that the optimum value is *an approximation*, as it is just the optimum from the input values of $K$ and $b$ provided on our grid. Let's take a look at the reported optimum values, which we can do with the syntax `LIST_NAME$VARIABLE_NAME`, where the dollar sign ($) helps identify which variable from the list you are investigating.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngause_likelihood$opt_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      K     b   l_hood log_lik\n  <dbl> <dbl>    <dbl> <lgl>  \n1  12.7 0.242 0.000348 FALSE  \n```\n\n\n:::\n:::\n\n\nIt is also important to visualize this likelihood function. For this dataset we have the two parameters $K$ and $b$, so the likelihood function will be a *likelihood surface*, rather than a two-dimensional plot. To visualize this in `R` we can use a contour diagram. @fig-gause-likely-plot displays this countour plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the likelihood values\nmy_likelihood <- gause_likelihood$likelihood\n\n# Make a contour plot\nggplot(data = my_likelihood) +\n  geom_tile(aes(x = K, y = b, fill = l_hood)) +\n  stat_contour(aes(x = K, y = b, z = l_hood))\n```\n\n::: {.cell-output-display}\n![Likelihood surface and contour lines for the `yeast` dataset.](09-likelihood_files/figure-html/fig-gause-likely-plot-1.png){#fig-gause-likely-plot width=672}\n:::\n:::\n\n\nSimilar to before, let's take this step by step:\n\n- The command `my_likelihood` just puts the likelihood values in a data frame.\n- The `ggplot` command is similar to that used before.\n- We use `geom_tile` to visualize the likelihood surface. There are three required inputs from the `my_likelihood` data frame: the `x` and `y` axis data values and the `fill` value, which represents the height of the likelihood function.\n- The command  `stat_contour` draws the contour lines, or places where the likelihood function has the same value. Notice how we used `z = l_hood` rather than `fill` here. This function helps \"smooth\" out any jaggedness in the contours.\n\nIn @fig-gause-likely-plot there appears to be a large region where the likelihood has the same value. (Admittedly I chose some broad parameter ranges for $K$ and $b$). We can refine that by producing a second contour plot that focuses in on parameters closer to the calculated optimum value at $K=13$ and $b=0.07$ (@fig-revised-gause-likelihood):\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      K     b   l_hood log_lik\n  <dbl> <dbl>    <dbl> <lgl>  \n1  12.8 0.241 0.000349 FALSE  \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Zoomed in likelihood surface. for the `yeast` dataset. The computed location of the optimum value is shown as a red point.](09-likelihood_files/figure-html/fig-revised-gause-likelihood-1.png){#fig-revised-gause-likelihood width=672}\n:::\n:::\n\n\nThe reported values for $K$ (12.8) and $b$ (0.241) may be close to what was reported from @fig-gause-likely-plot. Notice that in @fig-revised-gause-likelihood I also added in the location of the optimum point with `geom_point()`.\n\n\nAs a final step, once you have settled on the value that optimizes the likelihood function, is to compare the optimized parameters against the data (@fig-gause-model-data-09):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the parameters and the times to evaluate:\nmy_params <- gause_likelihood_rev$opt_value\ntime <- seq(0, 60, length.out = 100)\n\n# Get the right hand side of your equations\nnew_eq <- gause_model |>\n  formula.tools::rhs()\n\n# This collects the parameters and data into a list\nin_list <- c(my_params, time) |> as.list()\n\n# The eval command evaluates your model\nout_model <- eval(new_eq, envir = in_list)\n\n\n# Now collect everything into a data frame:\nmy_prediction <- tibble(time = time, volume = out_model)\n\n\nggplot() +\n  geom_point(\n    data = yeast,\n    aes(x = time, y = volume),\n    color = \"red\",\n    size = 2\n  ) +\n  geom_line(\n    data = my_prediction,\n    aes(x = time, y = volume)\n  ) +\n  labs(x = \"Time\", y = \"Volume\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Model and data comparison of the `yeast` dataset from maximum likelihood estimation.](09-likelihood_files/figure-html/fig-gause-model-data-09-1.png){#fig-gause-model-data-09 width=672}\n:::\n:::\n\n\n\nAll right, this code block has some new commands and techniques that need explaining. Once we have the parameter estimates we need to compute the modeled values.\n\n- First we define the `params` and the `time` we wish to evaluate with our model.\n- We need to evaluate the right hand side of $\\displaystyle y = \\frac{K}{1+e^{a+bt}}$, so the definition of `new_eq` helps to do that, using the package `formula.tools`.\n- The `|>` is the `tidyverse` [pipe](https://r4ds.had.co.nz/pipes.html#pipes). This is a very useful command to help make code more readable!\n- `in_list <- c(params,my_time) |> as.list()` collects the parameters and input times in one list to evaluate the model with `out_model <- eval(new_eq,envir=in_list)`\n- We make a data frame called `my_prediction` so we can then plot.\n\nAnd the rest of the plotting commands you should be used to. This activity focused on the likelihood function - Exercise \\@ref(exr:log-likelihood-yeast) has you repeat this analysis with the log-likelihood function.\n\n## Looking back and forward\nThis chapter covered a lot of ground - from probability and likelihood functions to computing and visualizing these. A good strategy for a likelihood function is to visualize the function and then explore to find values that optimize the likelihood or log-likelihood function. This approach is one example of *successive approximations* or using an iterative method to determine a solution.\\index{successive approximations} While this chapter focused on optimizing a likelihood function with one or two parameters, the successive approximation method does generalize to more parameters. However searching for parameters becomes tricky (read: tedious and slow) in high-dimensional spaces. In later chapters we will explore numerical methods to accelerate convergence to an optimum value. \n\n## Exercises\n\n::: {#exr-solve-gause}\nAlgebraically solve the equation $\\displaystyle 0.45 = \\frac{K}{1+e^{a}}$ for $a$.\n:::\n\n\n\n::: {#exr-show-small-likely}\nCompute the values of $L(b|\\vec{x},\\vec{y})$ and $\\ln(L(b|\\vec{x},\\vec{y}))$ for each of the data points in @eq-small-data-likely when $b=1.865$ and $\\sigma=1$. (This means that these 4 values would be multiplied or added when you compute the full likelihood function.) Explain if the likelihood or log-likelihood would be easier to calculate in instances when the number of observations is large. \n:::\n\n::: {#exr-log-likelihood-yeast}\nVisualize the likelihood function for the `yeast` dataset, but in this case report out and visualize the log-likelihood. (This means that you are setting the option `logLikely = TRUE` in the `compute_likelihood` function.)  Compare the log-likelihood surface to @fig-revised-gause-likelihood.\n:::\n\n\n::: {#exr-small-data-invest}\nWhen we generated our plot of the likelihood function in @fig-small-likelihood-plot we assumed that $\\sigma=1$ in Equation (9.6). For this exercise you will explore what happens in Equation (9.6) as $\\sigma$ increases or decreases.\n\n\na. Use [desmos](www.desmos.com/calculator) or `R` to generate a plot of @eq-small-data-likely. What happens to the shape of the likelihood function as $\\sigma$ increases?\nb. How does the estimate of $b$ change as $\\sigma$ changes?\nc. The spread of the distribution (in terms of it being more peaked or less peaked) is a measure of uncertainty of a parameter estimate. How does the resulting parameter uncertainty change as $\\sigma$ changes?\n\n:::\n\n::: {#exr-small-data-optimize}\nUsing @eq-small-data-likely with $\\sigma = 1$:\n\n\na. Apply the natural logarithm to both sides of this expression. Using properties of logarithms, show that the log-likelihood function is $\\displaystyle \\ln(L(b)) =-2 \\ln(2) - 2 \\ln (\\pi) -\\frac{(3-b)^{2}}{2}-\\frac{(5-2b)^{2}}{2}-\\frac{(4-4b)^{2}}{2}-\\frac{(10-4b)^{2}}{2}$.\n\nb. Make a plot of the log-likelihood function (in desmos or `R`).\n\nc. At what values of $b$ Where is this function optimized? Does your graph indicate that it is a maximum or a minimum value?\n  \nd. Compare this likelihood estimate for $b$ to what was found in @fig-small-likelihood-plot. \n\n:::\n\n\n::: {#exr-full-linear}\nConsider the linear model $y=a+bx$ for the following dataset:\n\n\n| *x* | *y*  | \n|:------:|:-----:|\n| 1 | 3 |\n| 2 | 5 |\n| 4 | 4 |\n| 4 | 10 |\n\n\na. With the function `compute_likelihood`, generate a contour plot of both the likelihood and log-likelihood functions. You may assume $0 \\leq a \\leq 5$ and $0 \\leq b \\leq 5$.\nb. Make a scatterplot of these data with the equation $y=a+bx$ with your maximum likelihood parameter estimates.\nc. Earlier when we fit $y=bx$ we found $b=1.865$. How does adding $a$ as a model parameter affect your estimate of $b$?\n\n:::\n\n\n::: {#exr-det-a-09}\nFor the function $\\displaystyle P(t)=\\frac{K}{1+e^{a+bt}}$, with $P(0)=P_{0}$, determine an expression for the parameter $a$ in terms of $K$, $b$, and $P_{0}$.\n:::\n\n::: {#exr-gause-ml-09}\nThe values returned by the maximum likelihood estimate for @eq-gause-09 were a little different from those reported in @gause_experimental_1932:\n\n\n**Parameter** | **Maximum Likelihood Estimate**  | **@gause_experimental_1932** \n|:------:|:-----:|:-----:|\n$K$ | 12.7 |  13.0 |\n$b$ | 0.24242 |  0.21827 |\n  \nUsing the `yeast` dataset, plot the function $\\displaystyle y = \\frac{K}{1+e^{a-bt}}$ (setting $\\displaystyle a = \\ln \\left( \\frac{K}{0.45} - 1 \\right)$) using both sets of parameters. Which approach (the Maximum Likelihood estimate or @gause_experimental_1932) does a better job representing the data?\n:::\n\n::: {#exr-nutrient-09}\nAn equation that relates a consumer's nutrient content (denoted as $y$) to the nutrient content of food (denoted as $x$) is given by: $\\displaystyle y = c x^{1/\\theta}$, where $\\theta \\geq 1$ and $c>0$ are both constants.\n\n\na. Use the dataset `phosphorous` to make a scatterplot with the variable `algae` on the horizontal axis, `daphnia` on the vertical axis.\nb. Generate a contour plot for the likelihood function for these data. You may assume $0 \\leq c \\leq 5$ and $1 \\leq \\theta \\leq 20$. What are the values of $c$ and $\\theta$ that optimize the likelihood? *Hint:* for the dataset `phosphorous` be sure to use the variables $x=$`algae` and $y=$`daphnia`.\nc. Add the fitted curve to your scatterplot and evaluate your fitted results.\n\n:::\n\n\n::: {#exr-wilson-log-09}\nA dog's weight $W$ (pounds) changes over $D$ days according to the following function:\n\n$$\nW =f(D,p_{1},p_{2})= \\frac{p_{1}}{1+e^{2.462-p_{2}D}},\n$$\n\nwhere $p_{1}$ and $p_{2}$ are parameters.\n\na. This function can be used to describe the data `wilson`. Make a scatterplot with the `wilson` data. What is the long term weight of the dog? \nb. Generate a contour plot for the likelihood function for these data. What are the values of $p_{1}$ and $p_{2}$ that optimize the likelihood?  *You may assume that $p_{1}$ and $p_{2}$ are both positive.*\nc. With your values of $p_{1}$ and $p_{2}$ add the function $W$ to your scatterplot and compare the fitted curve to the data.\n\n:::\n\n",
    "supporting": [
      "09-likelihood_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}