<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Probability and Likelihood Functions | Exploring Modeling with Data and Differential Equations Using R</title>
  <meta name="description" content="A textbook used for MAT 369 at Augsburg University." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Probability and Likelihood Functions | Exploring Modeling with Data and Differential Equations Using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A textbook used for MAT 369 at Augsburg University." />
  <meta name="github-repo" content="openscapes/series" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Probability and Likelihood Functions | Exploring Modeling with Data and Differential Equations Using R" />
  
  <meta name="twitter:description" content="A textbook used for MAT 369 at Augsburg University." />
  

<meta name="author" content="John M. Zobitz" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="linear-regression-08.html"/>
<link rel="next" href="cost-fns-10.html"/>
<script src="libs/header-attrs-2.14/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="lib/css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="lib/css/style.css" type="text/css" />
<link rel="stylesheet" href="lib/css/lesson.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>Modeling with Data and Differential Equations in R</strong><br>by John Zobitz</a></li>

<li class="divider"></li>
<li><a href="index.html#welcome">Welcome<span></span></a>
<ul>
<li><a href="index.html#computational-code">Computational code<span></span></a></li>
<li><a href="index.html#questions-comments-issues">Questions? Comments? Issues?<span></span></a></li>
<li><a href="index.html#about-the-cover">About the cover<span></span></a></li>
<li><a href="index.html#acknowledgments">Acknowledgments<span></span></a></li>
</ul></li>
<li class="part"><span><b>I Models with Differential Equations<span></span></b></span></li>
<li class="chapter" data-level="1" data-path="intro-01.html"><a href="intro-01.html"><i class="fa fa-check"></i><b>1</b> Models of Rates with Data<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro-01.html"><a href="intro-01.html#rates-of-change-in-the-world-a-model-is-born"><i class="fa fa-check"></i><b>1.1</b> Rates of change in the world: a model is born<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="intro-01.html"><a href="intro-01.html#modeling-in-context-the-spread-of-a-disease"><i class="fa fa-check"></i><b>1.2</b> Modeling in context: the spread of a disease<span></span></a></li>
<li class="chapter" data-level="1.3" data-path="intro-01.html"><a href="intro-01.html#model-solutions"><i class="fa fa-check"></i><b>1.3</b> Model solutions<span></span></a></li>
<li class="chapter" data-level="1.4" data-path="intro-01.html"><a href="intro-01.html#which-model-is-best"><i class="fa fa-check"></i><b>1.4</b> Which model is best?<span></span></a></li>
<li class="chapter" data-level="1.5" data-path="intro-01.html"><a href="intro-01.html#start-here"><i class="fa fa-check"></i><b>1.5</b> Start here<span></span></a></li>
<li class="chapter" data-level="1.6" data-path="intro-01.html"><a href="intro-01.html#exercises"><i class="fa fa-check"></i><b>1.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-intro-02.html"><a href="r-intro-02.html"><i class="fa fa-check"></i><b>2</b> Introduction to R<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-intro-02.html"><a href="r-intro-02.html#r-and-rstudio"><i class="fa fa-check"></i><b>2.1</b> <code>R</code> and RStudio<span></span></a></li>
<li class="chapter" data-level="2.2" data-path="r-intro-02.html"><a href="r-intro-02.html#first-steps-getting-acquainted-with-r"><i class="fa fa-check"></i><b>2.2</b> First steps: getting acquainted with <code>R</code><span></span></a></li>
<li class="chapter" data-level="2.3" data-path="r-intro-02.html"><a href="r-intro-02.html#increasing-functionality-with-packages"><i class="fa fa-check"></i><b>2.3</b> Increasing functionality with packages<span></span></a></li>
<li class="chapter" data-level="2.4" data-path="r-intro-02.html"><a href="r-intro-02.html#working-with-r-variables-data-frames-and-datasets"><i class="fa fa-check"></i><b>2.4</b> Working with <code>R</code>: variables, data frames, and datasets<span></span></a></li>
<li class="chapter" data-level="2.5" data-path="r-intro-02.html"><a href="r-intro-02.html#visualization-with-r"><i class="fa fa-check"></i><b>2.5</b> Visualization with <code>R</code><span></span></a></li>
<li class="chapter" data-level="2.6" data-path="r-intro-02.html"><a href="r-intro-02.html#defining-functions"><i class="fa fa-check"></i><b>2.6</b> Defining functions<span></span></a></li>
<li class="chapter" data-level="2.7" data-path="r-intro-02.html"><a href="r-intro-02.html#concluding-thoughts"><i class="fa fa-check"></i><b>2.7</b> Concluding thoughts<span></span></a></li>
<li class="chapter" data-level="2.8" data-path="r-intro-02.html"><a href="r-intro-02.html#exercises-1"><i class="fa fa-check"></i><b>2.8</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html"><i class="fa fa-check"></i><b>3</b> Modeling with Rates of Change<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html#competing-plant-species-and-equilibrium-solutions"><i class="fa fa-check"></i><b>3.1</b> Competing plant species and equilibrium solutions<span></span></a></li>
<li class="chapter" data-level="3.2" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html#the-law-of-mass-action"><i class="fa fa-check"></i><b>3.2</b> The Law of Mass Action<span></span></a></li>
<li class="chapter" data-level="3.3" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html#coupled-differential-equations-lynx-and-hares"><i class="fa fa-check"></i><b>3.3</b> Coupled differential equations: lynx and hares<span></span></a></li>
<li class="chapter" data-level="3.4" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html#functional-responses"><i class="fa fa-check"></i><b>3.4</b> Functional responses<span></span></a></li>
<li class="chapter" data-level="3.5" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html#exercises-2"><i class="fa fa-check"></i><b>3.5</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="euler-04.html"><a href="euler-04.html"><i class="fa fa-check"></i><b>4</b> Euler’s Method<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="euler-04.html"><a href="euler-04.html#the-flu-and-locally-linear-approximation"><i class="fa fa-check"></i><b>4.1</b> The flu and locally linear approximation<span></span></a></li>
<li class="chapter" data-level="4.2" data-path="euler-04.html"><a href="euler-04.html#a-workflow-for-approximation"><i class="fa fa-check"></i><b>4.2</b> A workflow for approximation<span></span></a></li>
<li class="chapter" data-level="4.3" data-path="euler-04.html"><a href="euler-04.html#building-an-iterative-method"><i class="fa fa-check"></i><b>4.3</b> Building an iterative method<span></span></a></li>
<li class="chapter" data-level="4.4" data-path="euler-04.html"><a href="euler-04.html#eulers-method-and-beyond"><i class="fa fa-check"></i><b>4.4</b> Euler’s method and beyond<span></span></a></li>
<li class="chapter" data-level="4.5" data-path="euler-04.html"><a href="euler-04.html#exercises-3"><i class="fa fa-check"></i><b>4.5</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="phase-05.html"><a href="phase-05.html"><i class="fa fa-check"></i><b>5</b> Phase Lines and Equilibrium Solutions<span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="phase-05.html"><a href="phase-05.html#equilibrium-solutions"><i class="fa fa-check"></i><b>5.1</b> Equilibrium solutions<span></span></a></li>
<li class="chapter" data-level="5.2" data-path="phase-05.html"><a href="phase-05.html#phase-lines-for-differential-equations"><i class="fa fa-check"></i><b>5.2</b> Phase lines for differential equations<span></span></a></li>
<li class="chapter" data-level="5.3" data-path="phase-05.html"><a href="phase-05.html#a-stability-test-for-equilibrium-solutions"><i class="fa fa-check"></i><b>5.3</b> A stability test for equilibrium solutions<span></span></a></li>
<li class="chapter" data-level="5.4" data-path="phase-05.html"><a href="phase-05.html#exercises-4"><i class="fa fa-check"></i><b>5.4</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="coupled-06.html"><a href="coupled-06.html"><i class="fa fa-check"></i><b>6</b> Coupled Systems of Equations<span></span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="coupled-06.html"><a href="coupled-06.html#flu-with-quarantine-and-equilibrium-solutions"><i class="fa fa-check"></i><b>6.1</b> Flu with quarantine and equilibrium solutions<span></span></a></li>
<li class="chapter" data-level="6.2" data-path="coupled-06.html"><a href="coupled-06.html#nullclines"><i class="fa fa-check"></i><b>6.2</b> Nullclines<span></span></a></li>
<li class="chapter" data-level="6.3" data-path="coupled-06.html"><a href="coupled-06.html#phase-planes"><i class="fa fa-check"></i><b>6.3</b> Phase planes<span></span></a></li>
<li class="chapter" data-level="6.4" data-path="coupled-06.html"><a href="coupled-06.html#generating-a-phase-plane-in-r"><i class="fa fa-check"></i><b>6.4</b> Generating a phase plane in <code>R</code><span></span></a></li>
<li class="chapter" data-level="6.5" data-path="coupled-06.html"><a href="coupled-06.html#slope-fields"><i class="fa fa-check"></i><b>6.5</b> Slope fields<span></span></a></li>
<li class="chapter" data-level="6.6" data-path="coupled-06.html"><a href="coupled-06.html#exercises-5"><i class="fa fa-check"></i><b>6.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="exact-solns-07.html"><a href="exact-solns-07.html"><i class="fa fa-check"></i><b>7</b> Exact Solutions to Differential Equations<span></span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="exact-solns-07.html"><a href="exact-solns-07.html#verify-a-solution"><i class="fa fa-check"></i><b>7.1</b> Verify a solution<span></span></a></li>
<li class="chapter" data-level="7.2" data-path="exact-solns-07.html"><a href="exact-solns-07.html#separable-differential-equations"><i class="fa fa-check"></i><b>7.2</b> Separable differential equations<span></span></a></li>
<li class="chapter" data-level="7.3" data-path="exact-solns-07.html"><a href="exact-solns-07.html#integrating-factors"><i class="fa fa-check"></i><b>7.3</b> Integrating factors<span></span></a></li>
<li class="chapter" data-level="7.4" data-path="exact-solns-07.html"><a href="exact-solns-07.html#verify-broad-07"><i class="fa fa-check"></i><b>7.4</b> Applying the verification method to coupled equations<span></span></a></li>
<li class="chapter" data-level="7.5" data-path="exact-solns-07.html"><a href="exact-solns-07.html#exercises-6"><i class="fa fa-check"></i><b>7.5</b> Exercises<span></span></a></li>
</ul></li>
<li class="part"><span><b>II Parameterizing Models with Data<span></span></b></span></li>
<li class="chapter" data-level="8" data-path="linear-regression-08.html"><a href="linear-regression-08.html"><i class="fa fa-check"></i><b>8</b> Linear Regression and Curve Fitting<span></span></a>
<ul>
<li class="chapter" data-level="8.1" data-path="linear-regression-08.html"><a href="linear-regression-08.html#what-is-parameter-estimation"><i class="fa fa-check"></i><b>8.1</b> What is parameter estimation?<span></span></a></li>
<li class="chapter" data-level="8.2" data-path="linear-regression-08.html"><a href="linear-regression-08.html#parameter-estimation-for-global-temperature-data"><i class="fa fa-check"></i><b>8.2</b> Parameter estimation for global temperature data<span></span></a></li>
<li class="chapter" data-level="8.3" data-path="linear-regression-08.html"><a href="linear-regression-08.html#beyond-linear-08"><i class="fa fa-check"></i><b>8.3</b> Moving beyond linear models for parameter estimation<span></span></a></li>
<li class="chapter" data-level="8.4" data-path="linear-regression-08.html"><a href="linear-regression-08.html#parameter-estimation-with-nonlinear-models"><i class="fa fa-check"></i><b>8.4</b> Parameter estimation with nonlinear models<span></span></a></li>
<li class="chapter" data-level="8.5" data-path="linear-regression-08.html"><a href="linear-regression-08.html#towards-model-data-fusion"><i class="fa fa-check"></i><b>8.5</b> Towards model-data fusion<span></span></a></li>
<li class="chapter" data-level="8.6" data-path="linear-regression-08.html"><a href="linear-regression-08.html#exercises-7"><i class="fa fa-check"></i><b>8.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="likelihood-09.html"><a href="likelihood-09.html"><i class="fa fa-check"></i><b>9</b> Probability and Likelihood Functions<span></span></a>
<ul>
<li class="chapter" data-level="9.1" data-path="likelihood-09.html"><a href="likelihood-09.html#linear-regression-on-a-small-dataset"><i class="fa fa-check"></i><b>9.1</b> Linear regression on a small dataset<span></span></a></li>
<li class="chapter" data-level="9.2" data-path="likelihood-09.html"><a href="likelihood-09.html#continuous-probability-density-functions"><i class="fa fa-check"></i><b>9.2</b> Continuous probability density functions<span></span></a></li>
<li class="chapter" data-level="9.3" data-path="likelihood-09.html"><a href="likelihood-09.html#connecting-probabilities-to-linear-regression"><i class="fa fa-check"></i><b>9.3</b> Connecting probabilities to linear regression<span></span></a></li>
<li class="chapter" data-level="9.4" data-path="likelihood-09.html"><a href="likelihood-09.html#visualizing-likelihood-surfaces"><i class="fa fa-check"></i><b>9.4</b> Visualizing likelihood surfaces<span></span></a></li>
<li class="chapter" data-level="9.5" data-path="likelihood-09.html"><a href="likelihood-09.html#looking-back-and-forward"><i class="fa fa-check"></i><b>9.5</b> Looking back and forward<span></span></a></li>
<li class="chapter" data-level="9.6" data-path="likelihood-09.html"><a href="likelihood-09.html#exercises-8"><i class="fa fa-check"></i><b>9.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="cost-fns-10.html"><a href="cost-fns-10.html"><i class="fa fa-check"></i><b>10</b> Cost Functions qnd Bayes’ Rule<span></span></a>
<ul>
<li class="chapter" data-level="10.1" data-path="cost-fns-10.html"><a href="cost-fns-10.html#cost-functions-and-model-data-residuals"><i class="fa fa-check"></i><b>10.1</b> Cost functions and model-data residuals<span></span></a></li>
<li class="chapter" data-level="10.2" data-path="cost-fns-10.html"><a href="cost-fns-10.html#further-extensions-to-the-cost-function"><i class="fa fa-check"></i><b>10.2</b> Further extensions to the cost function<span></span></a></li>
<li class="chapter" data-level="10.3" data-path="cost-fns-10.html"><a href="cost-fns-10.html#conditional-probabilities-and-bayes-rule"><i class="fa fa-check"></i><b>10.3</b> Conditional probabilities and Bayes’ rule<span></span></a></li>
<li class="chapter" data-level="10.4" data-path="cost-fns-10.html"><a href="cost-fns-10.html#bayes-rule-in-action"><i class="fa fa-check"></i><b>10.4</b> Bayes’ rule in action<span></span></a></li>
<li class="chapter" data-level="10.5" data-path="cost-fns-10.html"><a href="cost-fns-10.html#next-steps"><i class="fa fa-check"></i><b>10.5</b> Next steps<span></span></a></li>
<li class="chapter" data-level="10.6" data-path="cost-fns-10.html"><a href="cost-fns-10.html#exercises-9"><i class="fa fa-check"></i><b>10.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="bootstrap-11.html"><a href="bootstrap-11.html"><i class="fa fa-check"></i><b>11</b> Sampling Distributions and the Bootstrap Method<span></span></a>
<ul>
<li class="chapter" data-level="11.1" data-path="bootstrap-11.html"><a href="bootstrap-11.html#histograms-and-their-visualization"><i class="fa fa-check"></i><b>11.1</b> Histograms and their visualization<span></span></a></li>
<li class="chapter" data-level="11.2" data-path="bootstrap-11.html"><a href="bootstrap-11.html#statistical-theory-sampling-distributions"><i class="fa fa-check"></i><b>11.2</b> Statistical theory: sampling distributions<span></span></a></li>
<li class="chapter" data-level="11.3" data-path="bootstrap-11.html"><a href="bootstrap-11.html#summary-and-next-steps"><i class="fa fa-check"></i><b>11.3</b> Summary and next steps<span></span></a></li>
<li class="chapter" data-level="11.4" data-path="bootstrap-11.html"><a href="bootstrap-11.html#exercises-10"><i class="fa fa-check"></i><b>11.4</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="metropolis-12.html"><a href="metropolis-12.html"><i class="fa fa-check"></i><b>12</b> The Metropolis-Hastings Algorithm<span></span></a>
<ul>
<li class="chapter" data-level="12.1" data-path="metropolis-12.html"><a href="metropolis-12.html#estimating-the-growth-of-a-dog"><i class="fa fa-check"></i><b>12.1</b> Estimating the growth of a dog<span></span></a></li>
<li class="chapter" data-level="12.2" data-path="metropolis-12.html"><a href="metropolis-12.html#lr-12"><i class="fa fa-check"></i><b>12.2</b> Likelihood ratios for parameter estimation<span></span></a></li>
<li class="chapter" data-level="12.3" data-path="metropolis-12.html"><a href="metropolis-12.html#the-metropolis-hastings-algorithm-for-parameter-estimation"><i class="fa fa-check"></i><b>12.3</b> The Metropolis-Hastings algorithm for parameter estimation<span></span></a></li>
<li class="chapter" data-level="12.4" data-path="metropolis-12.html"><a href="metropolis-12.html#exercises-11"><i class="fa fa-check"></i><b>12.4</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="mcmc-13.html"><a href="mcmc-13.html"><i class="fa fa-check"></i><b>13</b> Markov Chain Monte Carlo Parameter Estimation<span></span></a>
<ul>
<li class="chapter" data-level="13.1" data-path="mcmc-13.html"><a href="mcmc-13.html#the-recipe-for-mcmc"><i class="fa fa-check"></i><b>13.1</b> The recipe for MCMC<span></span></a></li>
<li class="chapter" data-level="13.2" data-path="mcmc-13.html"><a href="mcmc-13.html#mcmc-parameter-estimation-with-an-empirical-model"><i class="fa fa-check"></i><b>13.2</b> MCMC parameter estimation with an empirical model<span></span></a></li>
<li class="chapter" data-level="13.3" data-path="mcmc-13.html"><a href="mcmc-13.html#mcmc-parameter-estimation-with-a-differential-equation-model"><i class="fa fa-check"></i><b>13.3</b> MCMC parameter estimation with a differential equation model<span></span></a></li>
<li class="chapter" data-level="13.4" data-path="mcmc-13.html"><a href="mcmc-13.html#timing-your-code"><i class="fa fa-check"></i><b>13.4</b> Timing your code<span></span></a></li>
<li class="chapter" data-level="13.5" data-path="mcmc-13.html"><a href="mcmc-13.html#further-extensions-to-mcmc"><i class="fa fa-check"></i><b>13.5</b> Further extensions to MCMC<span></span></a></li>
<li class="chapter" data-level="13.6" data-path="mcmc-13.html"><a href="mcmc-13.html#exercises-12"><i class="fa fa-check"></i><b>13.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="information-criteria-14.html"><a href="information-criteria-14.html"><i class="fa fa-check"></i><b>14</b> Information Criteria<span></span></a>
<ul>
<li class="chapter" data-level="14.1" data-path="information-criteria-14.html"><a href="information-criteria-14.html#model-assessment-guidelines"><i class="fa fa-check"></i><b>14.1</b> Model assessment guidelines<span></span></a></li>
<li class="chapter" data-level="14.2" data-path="information-criteria-14.html"><a href="information-criteria-14.html#information-criteria-for-assessing-competing-models"><i class="fa fa-check"></i><b>14.2</b> Information criteria for assessing competing models<span></span></a></li>
<li class="chapter" data-level="14.3" data-path="information-criteria-14.html"><a href="information-criteria-14.html#a-few-cautionary-notes"><i class="fa fa-check"></i><b>14.3</b> A few cautionary notes<span></span></a></li>
<li class="chapter" data-level="14.4" data-path="information-criteria-14.html"><a href="information-criteria-14.html#exercises-13"><i class="fa fa-check"></i><b>14.4</b> Exercises<span></span></a></li>
</ul></li>
<li class="part"><span><b>III Stability Analysis for Differential Equations<span></span></b></span></li>
<li class="chapter" data-level="15" data-path="linearsystems-15.html"><a href="linearsystems-15.html"><i class="fa fa-check"></i><b>15</b> Systems of Linear Differential Equations<span></span></a>
<ul>
<li class="chapter" data-level="15.1" data-path="linearsystems-15.html"><a href="linearsystems-15.html#linear-systems-of-differential-equations-and-matrix-notation"><i class="fa fa-check"></i><b>15.1</b> Linear systems of differential equations and matrix notation<span></span></a></li>
<li class="chapter" data-level="15.2" data-path="linearsystems-15.html"><a href="linearsystems-15.html#equilibrium-solutions-1"><i class="fa fa-check"></i><b>15.2</b> Equilibrium solutions<span></span></a></li>
<li class="chapter" data-level="15.3" data-path="linearsystems-15.html"><a href="linearsystems-15.html#the-phase-plane"><i class="fa fa-check"></i><b>15.3</b> The phase plane<span></span></a></li>
<li class="chapter" data-level="15.4" data-path="linearsystems-15.html"><a href="linearsystems-15.html#non-equilibrium-solutions-and-their-stability"><i class="fa fa-check"></i><b>15.4</b> Non-equilibrium solutions and their stability<span></span></a></li>
<li class="chapter" data-level="15.5" data-path="linearsystems-15.html"><a href="linearsystems-15.html#exercises-14"><i class="fa fa-check"></i><b>15.5</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="nonlinear-16.html"><a href="nonlinear-16.html"><i class="fa fa-check"></i><b>16</b> Systems of Nonlinear Differential Equations<span></span></a>
<ul>
<li class="chapter" data-level="16.1" data-path="nonlinear-16.html"><a href="nonlinear-16.html#introducing-nonlinear-systems-of-differential-equations"><i class="fa fa-check"></i><b>16.1</b> Introducing nonlinear systems of differential equations<span></span></a></li>
<li class="chapter" data-level="16.2" data-path="nonlinear-16.html"><a href="nonlinear-16.html#zooming-in-on-the-phase-plane"><i class="fa fa-check"></i><b>16.2</b> Zooming in on the phase plane<span></span></a></li>
<li class="chapter" data-level="16.3" data-path="nonlinear-16.html"><a href="nonlinear-16.html#determining-equilibrium-solutions-with-nullclines"><i class="fa fa-check"></i><b>16.3</b> Determining equilibrium solutions with nullclines<span></span></a></li>
<li class="chapter" data-level="16.4" data-path="nonlinear-16.html"><a href="nonlinear-16.html#stability-of-an-equilibrium-solution"><i class="fa fa-check"></i><b>16.4</b> Stability of an equilibrium solution<span></span></a></li>
<li class="chapter" data-level="16.5" data-path="nonlinear-16.html"><a href="nonlinear-16.html#graphing-nullclines-in-a-phase-plane"><i class="fa fa-check"></i><b>16.5</b> Graphing nullclines in a phase plane<span></span></a></li>
<li class="chapter" data-level="16.6" data-path="nonlinear-16.html"><a href="nonlinear-16.html#exercises-15"><i class="fa fa-check"></i><b>16.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="jacobian-17.html"><a href="jacobian-17.html"><i class="fa fa-check"></i><b>17</b> Local Linearization and the Jacobian<span></span></a>
<ul>
<li class="chapter" data-level="17.1" data-path="jacobian-17.html"><a href="jacobian-17.html#competing-populations"><i class="fa fa-check"></i><b>17.1</b> Competing populations<span></span></a></li>
<li class="chapter" data-level="17.2" data-path="jacobian-17.html"><a href="jacobian-17.html#tangent-plane-approximations"><i class="fa fa-check"></i><b>17.2</b> Tangent plane approximations<span></span></a></li>
<li class="chapter" data-level="17.3" data-path="jacobian-17.html"><a href="jacobian-17.html#the-jacobian-matrix"><i class="fa fa-check"></i><b>17.3</b> The Jacobian matrix<span></span></a></li>
<li class="chapter" data-level="17.4" data-path="jacobian-17.html"><a href="jacobian-17.html#exercises-16"><i class="fa fa-check"></i><b>17.4</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html"><i class="fa fa-check"></i><b>18</b> What are Eigenvalues?<span></span></a>
<ul>
<li class="chapter" data-level="18.1" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#introduction"><i class="fa fa-check"></i><b>18.1</b> Introduction<span></span></a></li>
<li class="chapter" data-level="18.2" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#straight-line-solutions"><i class="fa fa-check"></i><b>18.2</b> Straight line solutions<span></span></a></li>
<li class="chapter" data-level="18.3" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#computing-eigenvalues-and-eigenvectors"><i class="fa fa-check"></i><b>18.3</b> Computing eigenvalues and eigenvectors<span></span></a></li>
<li class="chapter" data-level="18.4" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#what-do-eigenvalues-tell-us"><i class="fa fa-check"></i><b>18.4</b> What do eigenvalues tell us?<span></span></a></li>
<li class="chapter" data-level="18.5" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#concluding-thoughts-1"><i class="fa fa-check"></i><b>18.5</b> Concluding thoughts<span></span></a></li>
<li class="chapter" data-level="18.6" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#exercises-17"><i class="fa fa-check"></i><b>18.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="stability-19.html"><a href="stability-19.html"><i class="fa fa-check"></i><b>19</b> Qualitative Stability Analysis<span></span></a>
<ul>
<li class="chapter" data-level="19.1" data-path="stability-19.html"><a href="stability-19.html#the-characteristic-polynomial-again"><i class="fa fa-check"></i><b>19.1</b> The characteristic polynomial (again)<span></span></a></li>
<li class="chapter" data-level="19.2" data-path="stability-19.html"><a href="stability-19.html#stability-with-the-trace-and-determinant"><i class="fa fa-check"></i><b>19.2</b> Stability with the trace and determinant<span></span></a></li>
<li class="chapter" data-level="19.3" data-path="stability-19.html"><a href="stability-19.html#a-workflow-for-stability-analysis"><i class="fa fa-check"></i><b>19.3</b> A workflow for stability analysis<span></span></a></li>
<li class="chapter" data-level="19.4" data-path="stability-19.html"><a href="stability-19.html#stability-for-higher-order-systems-of-differential-equations."><i class="fa fa-check"></i><b>19.4</b> Stability for higher-order systems of differential equations.<span></span></a></li>
<li class="chapter" data-level="19.5" data-path="stability-19.html"><a href="stability-19.html#exercises-18"><i class="fa fa-check"></i><b>19.5</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="bifurcation-20.html"><a href="bifurcation-20.html"><i class="fa fa-check"></i><b>20</b> Bifurcation<span></span></a>
<ul>
<li class="chapter" data-level="20.1" data-path="bifurcation-20.html"><a href="bifurcation-20.html#a-series-of-equations"><i class="fa fa-check"></i><b>20.1</b> A series of equations<span></span></a></li>
<li class="chapter" data-level="20.2" data-path="bifurcation-20.html"><a href="bifurcation-20.html#bifurcations-with-systems-of-equations"><i class="fa fa-check"></i><b>20.2</b> Bifurcations with systems of equations<span></span></a></li>
<li class="chapter" data-level="20.3" data-path="bifurcation-20.html"><a href="bifurcation-20.html#functions-as-equilibrium-solutions-limit-cycles"><i class="fa fa-check"></i><b>20.3</b> Functions as equilibrium solutions: limit cycles<span></span></a></li>
<li class="chapter" data-level="20.4" data-path="bifurcation-20.html"><a href="bifurcation-20.html#bifurcations-as-analysis-tools"><i class="fa fa-check"></i><b>20.4</b> Bifurcations as analysis tools<span></span></a></li>
<li class="chapter" data-level="20.5" data-path="bifurcation-20.html"><a href="bifurcation-20.html#exercises-19"><i class="fa fa-check"></i><b>20.5</b> Exercises<span></span></a></li>
</ul></li>
<li class="part"><span><b>IV Stochastic Differential Equations<span></span></b></span></li>
<li class="chapter" data-level="21" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html"><i class="fa fa-check"></i><b>21</b> Stochastic Biological Systems<span></span></a>
<ul>
<li class="chapter" data-level="21.1" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html#introducing-stochastic-effects"><i class="fa fa-check"></i><b>21.1</b> Introducing stochastic effects<span></span></a></li>
<li class="chapter" data-level="21.2" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html#a-discrete-dynamical-system"><i class="fa fa-check"></i><b>21.2</b> A discrete dynamical system<span></span></a></li>
<li class="chapter" data-level="21.3" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html#environmental-stochasticity"><i class="fa fa-check"></i><b>21.3</b> Environmental stochasticity<span></span></a></li>
<li class="chapter" data-level="21.4" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html#discrete-systems-of-equations"><i class="fa fa-check"></i><b>21.4</b> Discrete systems of equations<span></span></a></li>
<li class="chapter" data-level="21.5" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html#exercises-20"><i class="fa fa-check"></i><b>21.5</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="stoch-sim-22.html"><a href="stoch-sim-22.html"><i class="fa fa-check"></i><b>22</b> Simulating and Visualizing Randomness<span></span></a>
<ul>
<li class="chapter" data-level="22.1" data-path="stoch-sim-22.html"><a href="stoch-sim-22.html#ensemble-averages"><i class="fa fa-check"></i><b>22.1</b> Ensemble averages<span></span></a></li>
<li class="chapter" data-level="22.2" data-path="stoch-sim-22.html"><a href="stoch-sim-22.html#repeated-iteration"><i class="fa fa-check"></i><b>22.2</b> Repeated iteration<span></span></a></li>
<li class="chapter" data-level="22.3" data-path="stoch-sim-22.html"><a href="stoch-sim-22.html#exercises-21"><i class="fa fa-check"></i><b>22.3</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="random-walks-23.html"><a href="random-walks-23.html"><i class="fa fa-check"></i><b>23</b> Random Walks<span></span></a>
<ul>
<li class="chapter" data-level="23.1" data-path="random-walks-23.html"><a href="random-walks-23.html#random-walk-on-a-number-line"><i class="fa fa-check"></i><b>23.1</b> Random walk on a number line<span></span></a></li>
<li class="chapter" data-level="23.2" data-path="random-walks-23.html"><a href="random-walks-23.html#iteration-and-ensemble-averages"><i class="fa fa-check"></i><b>23.2</b> Iteration and ensemble averages<span></span></a></li>
<li class="chapter" data-level="23.3" data-path="random-walks-23.html"><a href="random-walks-23.html#random-walk-mathematics"><i class="fa fa-check"></i><b>23.3</b> Random walk mathematics<span></span></a></li>
<li class="chapter" data-level="23.4" data-path="random-walks-23.html"><a href="random-walks-23.html#continuous-random-walks-and-diffusion"><i class="fa fa-check"></i><b>23.4</b> Continuous random walks and diffusion<span></span></a></li>
<li class="chapter" data-level="23.5" data-path="random-walks-23.html"><a href="random-walks-23.html#exercises-22"><i class="fa fa-check"></i><b>23.5</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="diffusion-24.html"><a href="diffusion-24.html"><i class="fa fa-check"></i><b>24</b> Diffusion and Brownian Motion<span></span></a>
<ul>
<li class="chapter" data-level="24.1" data-path="diffusion-24.html"><a href="diffusion-24.html#random-walk-redux"><i class="fa fa-check"></i><b>24.1</b> Random walk redux<span></span></a></li>
<li class="chapter" data-level="24.2" data-path="diffusion-24.html"><a href="diffusion-24.html#simulating-brownian-motion"><i class="fa fa-check"></i><b>24.2</b> Simulating Brownian motion<span></span></a></li>
<li class="chapter" data-level="24.3" data-path="diffusion-24.html"><a href="diffusion-24.html#exercises-23"><i class="fa fa-check"></i><b>24.3</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="sdes-25.html"><a href="sdes-25.html"><i class="fa fa-check"></i><b>25</b> Simulating Stochastic Differential Equations<span></span></a>
<ul>
<li class="chapter" data-level="25.1" data-path="sdes-25.html"><a href="sdes-25.html#the-stochastic-logistic-model"><i class="fa fa-check"></i><b>25.1</b> The stochastic logistic model<span></span></a></li>
<li class="chapter" data-level="25.2" data-path="sdes-25.html"><a href="sdes-25.html#the-euler-maruyama-method"><i class="fa fa-check"></i><b>25.2</b> The Euler-Maruyama method<span></span></a></li>
<li class="chapter" data-level="25.3" data-path="sdes-25.html"><a href="sdes-25.html#adding-stochasticity-to-parameters"><i class="fa fa-check"></i><b>25.3</b> Adding stochasticity to parameters<span></span></a></li>
<li class="chapter" data-level="25.4" data-path="sdes-25.html"><a href="sdes-25.html#systems-of-stochastic-differential-equations"><i class="fa fa-check"></i><b>25.4</b> Systems of stochastic differential equations<span></span></a></li>
<li class="chapter" data-level="25.5" data-path="sdes-25.html"><a href="sdes-25.html#concluding-thoughts-2"><i class="fa fa-check"></i><b>25.5</b> Concluding thoughts<span></span></a></li>
<li class="chapter" data-level="25.6" data-path="sdes-25.html"><a href="sdes-25.html#exercises-24"><i class="fa fa-check"></i><b>25.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="simul-stoch-26.html"><a href="simul-stoch-26.html"><i class="fa fa-check"></i><b>26</b> Statistics of a Stochastic Differential Equation<span></span></a>
<ul>
<li class="chapter" data-level="26.1" data-path="simul-stoch-26.html"><a href="simul-stoch-26.html#expected-value-of-a-stochastic-process"><i class="fa fa-check"></i><b>26.1</b> Expected value of a stochastic process<span></span></a></li>
<li class="chapter" data-level="26.2" data-path="simul-stoch-26.html"><a href="simul-stoch-26.html#birth-death-processes"><i class="fa fa-check"></i><b>26.2</b> Birth-death processes<span></span></a></li>
<li class="chapter" data-level="26.3" data-path="simul-stoch-26.html"><a href="simul-stoch-26.html#wrapping-up"><i class="fa fa-check"></i><b>26.3</b> Wrapping up<span></span></a></li>
<li class="chapter" data-level="26.4" data-path="simul-stoch-26.html"><a href="simul-stoch-26.html#exercises-25"><i class="fa fa-check"></i><b>26.4</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="solvingSDEs-27.html"><a href="solvingSDEs-27.html"><i class="fa fa-check"></i><b>27</b> Solutions to Stochastic Differential Equations<span></span></a>
<ul>
<li class="chapter" data-level="27.1" data-path="solvingSDEs-27.html"><a href="solvingSDEs-27.html#meet-the-fokker-planck-equation"><i class="fa fa-check"></i><b>27.1</b> Meet the Fokker-Planck equation<span></span></a></li>
<li class="chapter" data-level="27.2" data-path="solvingSDEs-27.html"><a href="solvingSDEs-27.html#deterministically-the-end"><i class="fa fa-check"></i><b>27.2</b> Deterministically the end<span></span></a></li>
<li class="chapter" data-level="27.3" data-path="solvingSDEs-27.html"><a href="solvingSDEs-27.html#exercises-26"><i class="fa fa-check"></i><b>27.3</b> Exercises<span></span></a></li>
</ul></li>
<li><a href="references.html#references">References<span></span></a></li>
<li class="divider"></li>
<li><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a></li>
<li><a href="https://bookdown.org" target="_blank">Built with Bookdown + RStudio</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Exploring Modeling with Data and Differential Equations Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="likelihood-09" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Probability and Likelihood Functions<a href="likelihood-09.html#likelihood-09" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In Chapter <a href="linear-regression-08.html#linear-regression-08">8</a> we began to the process of parameter estimation. We revisit parameter estimation here by applying <em>likelihood functions</em>, which is a topic from probability and statistics. Probability is the association of a set of observable events to a quantitative scale between 0 and 1. Informally, a value of zero means that event is not possible; 1 means that it definitely can happen.<a href="#fn28" class="footnote-ref" id="fnref28"><sup>28</sup></a> We will only consider continuous events with the range of parameter estimation problems examined here.</p>
<p>This chapter will introduce likelihood functions but also discuss some interesting visualization techniques of multivariable functions and contour plots. As with Chapter <a href="linear-regression-08.html#linear-regression-08">8</a> we are starting to build out some <code>R</code> skills and techniques that you can apply in other contexts. Let’s get started!</p>
<div id="linear-regression-on-a-small-dataset" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Linear regression on a small dataset<a href="likelihood-09.html#linear-regression-on-a-small-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Table <a href="likelihood-09.html#tab:limited-data-09">9.1</a> displays a dataset with a limited number of points where we wish to fit the function <span class="math inline">\(y=bx\)</span>:</p>
<table>
<caption><span id="tab:limited-data-09">TABLE 9.1: </span> A small, limited dataset.</caption>
<thead>
<tr class="header">
<th align="center"><em>x</em></th>
<th align="center">1</th>
<th align="center">2</th>
<th align="center">4</th>
<th align="center">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><em>y</em></td>
<td align="center">3</td>
<td align="center">5</td>
<td align="center">4</td>
<td align="center">10</td>
</tr>
</tbody>
</table>
<p>For this example we are forcing the intercept term to equal zero - for most cases you will just fit the linear equation (see Exercise <a href="likelihood-09.html#exr:full-linear">9.6</a> where you will consider the intercept <span class="math inline">\(a\)</span>). Figure <a href="likelihood-09.html#fig:quick-scatter-09">9.1</a> displays a quick scatterplot of these data:</p>
<div class="figure"><span id="fig:quick-scatter-09"></span>
<img src="explore-model-zobitz-220419_files/figure-html/quick-scatter-09-1.png" alt="A scatterplot of a small, limited dataset (Table \@ref(tab:limited-data-09))." width="672" />
<p class="caption">
FIGURE 9.1: A scatterplot of a small, limited dataset (Table <a href="likelihood-09.html#tab:limited-data-09">9.1</a>).
</p>
</div>
<p>The goal here is to work to determine the value of <span class="math inline">\(b\)</span> that is most <em>likely</em> - or consistent - with the data. However, before we tackle this further we need to understand how to quantify most <em>likely</em> in a mathematical sense. In order to do this, we need to take a quick excursion into continuous probability distributions.</p>
</div>
<div id="continuous-probability-density-functions" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Continuous probability density functions<a href="likelihood-09.html#continuous-probability-density-functions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Consider Figure <a href="likelihood-09.html#fig:normal-shaded-09">9.2</a>, which may be familiar to you as the normal distribution or the bell curve:</p>
<div class="figure"><span id="fig:normal-shaded-09"></span>
<img src="explore-model-zobitz-220419_files/figure-html/normal-shaded-09-1.png" alt="The standard normal distribution, with a shaded area between $x=\pm 1$" width="672" />
<p class="caption">
FIGURE 9.2: The standard normal distribution, with a shaded area between <span class="math inline">\(x=\pm 1\)</span>
</p>
</div>
<p>We tend to think of the plot and the associated function <span class="math inline">\(f(x)\)</span> as something with input and output (such as <span class="math inline">\(f(0)=\)</span> 0.3989). However because it is a probability density function, the <em>area</em> between two points yields the probability of an event to fall within two values as shown in Figure <a href="likelihood-09.html#fig:normal-shaded-09">9.2</a>.</p>
<p>In this case, the numerical value of the shaded area would represent the probability that our measurement is in the interval <span class="math inline">\(-1 \leq x \leq 1\)</span>. The value of the area, or the probability, is 0.68269. Perhaps when you studied calculus the area was expressed as a definite integral: <span class="math inline">\(\displaystyle \int_{-1}^{1} f(x) \; dx=\)</span> 0.68269, where <span class="math inline">\(f(x)\)</span> is the formula for the probability density function for the normal distribution. Here, the formula for the normal distribution <span class="math inline">\(f(x)\)</span> is given by Equation <a href="likelihood-09.html#eq:normal-09">(9.1)</a>, where <span class="math inline">\(\mu\)</span> is the mean and <span class="math inline">\(\sigma\)</span> is the standard deviation.<a href="#fn29" class="footnote-ref" id="fnref29"><sup>29</sup></a></p>
<p><span class="math display" id="eq:normal-09">\[\begin{equation}
f(x)=\frac{1}{\sqrt{2 \pi} \sigma } e^{-(x-\mu)^{2}/(2 \sigma^{2})} \tag{9.1}
\end{equation}\]</span></p>
<p>With this intuition we can summarize key facts about probability density functions:</p>
<ul>
<li><span class="math inline">\(f(x) \geq 0\)</span> (this means that probability density functions are positive values)</li>
<li>Area integrates to one (in probability, this means we have accounted for all of our outcomes)</li>
</ul>
</div>
<div id="connecting-probabilities-to-linear-regression" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Connecting probabilities to linear regression<a href="likelihood-09.html#connecting-probabilities-to-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we have made that small excursion into probability, let’s return to the parameter estimation problem. Another way to phrase this problem is to examine the probability distribution of the model-data residual for each measurement <span class="math inline">\(\epsilon_{i}\)</span> (Equation <a href="likelihood-09.html#eq:model-data-resid-09">(9.2)</a>):</p>
<p><span class="math display" id="eq:model-data-resid-09">\[\begin{equation}
\epsilon_{i} = y_{i} - f(x_{i},\vec{\alpha} ). \tag{9.2}
\end{equation}\]</span></p>
<p>The approach with likelihood functions assumes a particular probability distribution on each residual. One common assumption is that the model-data residual is normally distributed. In most applications the mean of this distribution is zero (<span class="math inline">\(\mu=0\)</span>) and the standard deviation <span class="math inline">\(\sigma\)</span> (which could be specified as measurement error, etc.). We formalize this assumption with a likelihood function <span class="math inline">\(L\)</span> in Equation <a href="likelihood-09.html#eq:likelihood-resid-09">(9.3)</a>.</p>
<p><span class="math display" id="eq:likelihood-resid-09">\[\begin{equation}
L(\epsilon_{i}) = \frac{1}{\sqrt{2 \pi} \sigma} e^{-\epsilon_{i}^{2} / 2 \sigma^{2} } \tag{9.3}
\end{equation}\]</span></p>
<p>To extend this further across all measurements, we use the idea of <em>independent, identically distributed</em> measurements so the joint likelihood of <strong>all</strong> the residuals (each <span class="math inline">\(\epsilon_{i}\)</span>) is the product of the individual likelihoods (Equation <a href="likelihood-09.html#eq:likelihood-prod-09">(9.4)</a>. The assumption of independent, identically distributed is a common one. As a note of caution you should always evaluate if this is a valid assumption for more advanced applications.</p>
<p><span class="math display" id="eq:likelihood-prod-09">\[\begin{equation}
L(\vec{\epsilon}) = \prod_{i=1}^{N} \frac{1}{\sqrt{2 \pi} \sigma} e^{-\epsilon_{i}^{2} / 2 \sigma^{2} } \tag{9.4}
\end{equation}\]</span></p>
<p>We are making progress here; however to fully characterize the solution we need to specify the parameters <span class="math inline">\(\vec{\alpha}\)</span>. A simple redefining of the likelihood function where we specify the measurements (<span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>) and parameters (<span class="math inline">\(\vec{\alpha}\)</span>) is all we need (Equation <a href="likelihood-09.html#eq:likelihood-prod-param-09">(9.5)</a>).</p>
<p><span class="math display" id="eq:likelihood-prod-param-09">\[\begin{equation}
L(\vec{\alpha} | \vec{x},\vec{y} )= \prod_{i=1}^{N}  \frac{1}{\sqrt{2 \pi} \sigma} \exp(-(y_{i} - f(x_{i},\vec{\alpha} ))^{2} / 2 \sigma^{2} )  \tag{9.5}
\end{equation}\]</span></p>
<p>Now with Equation <a href="likelihood-09.html#eq:likelihood-prod-param-09">(9.5)</a> we have a function where the best parameter estimate is the one that optimizes the likelihood.</p>
<p>Returning to our original linear regression problem (Table <a href="likelihood-09.html#tab:limited-data-09">9.1</a> and Figure <a href="likelihood-09.html#fig:quick-scatter-09">9.1</a>), we want to determine the <span class="math inline">\(b\)</span> for the function <span class="math inline">\(y=bx\)</span>. Equation <a href="likelihood-09.html#eq:small-data-likely">(9.6)</a> then characterizes the likelihood of <span class="math inline">\(b\)</span>, given the data <span class="math inline">\(\vec{x}\)</span> and <span class="math inline">\(\vec{y}\)</span>:</p>
<p><span class="math display" id="eq:small-data-likely">\[\begin{equation}
L(b | \vec{x},\vec{y} ) = \left( \frac{1}{\sqrt{2 \pi} \sigma}\right)^{4} e^{-\frac{(3-b)^{2}}{2\sigma^{2}}} \cdot e^{-\frac{(5-2b)^{2}}{2\sigma^{2}}}  \cdot e^{-\frac{(4-4b)^{2}}{2\sigma^{2}}}  \cdot e^{-\frac{(10-4b)^{2}}{2\sigma^{2}}} \tag{9.6}
\end{equation}\]</span></p>
<p>For the purposes of our argument here, we will assume <span class="math inline">\(\sigma=1\)</span>. Figure <a href="likelihood-09.html#fig:small-likelihood-plot">9.3</a> shows a plot of the likelihood function <span class="math inline">\(L(b | \vec{x},\vec{y} )\)</span>.</p>
<div class="figure"><span id="fig:small-likelihood-plot"></span>
<img src="explore-model-zobitz-220419_files/figure-html/small-likelihood-plot-1.png" alt="The likelihood function (Equation \@ref(eq:small-data-likely)) for the small dataset (Table \@ref(tab:limited-data-09)), with the value of the maximum likelihood at $b=1.865$ marked with a vertical line." width="672" />
<p class="caption">
FIGURE 9.3: The likelihood function (Equation <a href="likelihood-09.html#eq:small-data-likely">(9.6)</a>) for the small dataset (Table <a href="likelihood-09.html#tab:limited-data-09">9.1</a>), with the value of the maximum likelihood at <span class="math inline">\(b=1.865\)</span> marked with a vertical line.
</p>
</div>
<p>Note that in Figure <a href="likelihood-09.html#fig:small-likelihood-plot">9.3</a> the values of <span class="math inline">\(L(b | \vec{x},\vec{y} )\)</span> on the vertical axis are really small. (This typically may be the case; see Exercise <a href="likelihood-09.html#exr:show-small-likely">9.2</a>.) An alternative to the small numbers in <span class="math inline">\(L(b)\)</span> is to use the log-likelihood (Equation <a href="likelihood-09.html#eq:loglikely">(9.7)</a>):</p>
<p><span class="math display" id="eq:loglikely">\[\begin{equation}
\begin{split}
\ln(L(\vec{\alpha} | \vec{x},\vec{y} )) &amp;=  N \ln \left( \frac{1}{\sqrt{2 \pi} \sigma} \right) - \sum_{i=1}^{N} \frac{ (y_{i} - f(x_{i},\vec{\alpha} )^{2}}{ 2 \sigma^{2}} \\
 &amp; = - \frac{N}{2} \ln (2) - \frac{N}{2} \ln(\pi) - N \ln( \sigma) - \sum_{i=1}^{N} \frac{ (y_{i} - f(x_{i},\vec{\alpha} )^{2}}{ 2 \sigma^{2}}
\end{split} \tag{9.7}
\end{equation}\]</span></p>
<p>In Exercise <a href="likelihood-09.html#exr:small-data-optimize">9.5</a> you will be working on how to transform the likelihood function <span class="math inline">\(L(b)\)</span> to the log-likelihood <span class="math inline">\(\ln(L(b))\)</span> and showing that Equation <a href="likelihood-09.html#eq:small-data-likely">(9.6)</a> is maximized at <span class="math inline">\(b=1.865\)</span>. The data with the fitted line is shown in Figure <a href="likelihood-09.html#fig:quick-scatter-fit-09">9.4</a>.</p>
<div class="figure"><span id="fig:quick-scatter-fit-09"></span>
<img src="explore-model-zobitz-220419_files/figure-html/quick-scatter-fit-09-1.png" alt="A scatterplot of a small dataset (Table \@ref(tab:limited-data-09)) with fitted line $y=1.865x$ from optimizing Equation \@ref(eq:small-data-likely)." width="672" />
<p class="caption">
FIGURE 9.4: A scatterplot of a small dataset (Table <a href="likelihood-09.html#tab:limited-data-09">9.1</a>) with fitted line <span class="math inline">\(y=1.865x\)</span> from optimizing Equation <a href="likelihood-09.html#eq:small-data-likely">(9.6)</a>.
</p>
</div>
</div>
<div id="visualizing-likelihood-surfaces" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> Visualizing likelihood surfaces<a href="likelihood-09.html#visualizing-likelihood-surfaces" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Next we are going to examine a second example from <span class="citation"><a href="#ref-gause_experimental_1932" role="doc-biblioref">Gause</a> (<a href="#ref-gause_experimental_1932" role="doc-biblioref">1932</a>)</span> which modeled the growing of yeast in solution. This classic paper examines the biological principal of <em>competitive exclusion</em>, how one species can out-compete another one for resources. Some of the data from <span class="citation"><a href="#ref-gause_experimental_1932" role="doc-biblioref">Gause</a> (<a href="#ref-gause_experimental_1932" role="doc-biblioref">1932</a>)</span> is encoded in the data frame <code>yeast</code> in the <code>demodelr</code> package. For this example we are going to examine a model for one species growing without competition. Figure <a href="likelihood-09.html#fig:yeast-quick-09">9.5</a> shows a scatterplot of the <code>yeast</code> data.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="likelihood-09.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Make a quick ggplot of the data</span></span>
<span id="cb38-2"><a href="likelihood-09.html#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="likelihood-09.html#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb38-4"><a href="likelihood-09.html#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb38-5"><a href="likelihood-09.html#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> yeast,</span>
<span id="cb38-6"><a href="likelihood-09.html#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> volume),</span>
<span id="cb38-7"><a href="likelihood-09.html#cb38-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb38-8"><a href="likelihood-09.html#cb38-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">2</span></span>
<span id="cb38-9"><a href="likelihood-09.html#cb38-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-10"><a href="likelihood-09.html#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Volume&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:yeast-quick-09"></span>
<img src="explore-model-zobitz-220419_files/figure-html/yeast-quick-09-1.png" alt="Scatterplot of *Sacchromyces* volume growing by itself in a container." width="672" />
<p class="caption">
FIGURE 9.5: Scatterplot of <em>Sacchromyces</em> volume growing by itself in a container.
</p>
</div>
<p>We are going to assume the population of yeast (represented with the measurement of volume) over time changes according to the differential equation <span class="math inline">\(\displaystyle \frac{dy}{dt} = -by \frac{(K-y)}{K}\)</span>, where <span class="math inline">\(y\)</span> is the population of the yeast, and <span class="math inline">\(b\)</span> represents the growth rate, and <span class="math inline">\(K\)</span> is the carrying capacity of the population.</p>
<p>Equation <a href="likelihood-09.html#eq:gause-09">(9.8)</a> shows the solution to this differential equation, where the additional parameter <span class="math inline">\(a\)</span> can be found through application of the initial condition <span class="math inline">\(y_{0}\)</span>.</p>
<p><span class="math display" id="eq:gause-09">\[\begin{equation}
y = \frac{K}{1+e^{a-bt}} \tag{9.8}
\end{equation}\]</span></p>
<p>In <span class="citation"><a href="#ref-gause_experimental_1932" role="doc-biblioref">Gause</a> (<a href="#ref-gause_experimental_1932" role="doc-biblioref">1932</a>)</span> the value of <span class="math inline">\(a\)</span> was determined by solving the initial value problem <span class="math inline">\(y(0)=0.45\)</span>. In Exercise <a href="likelihood-09.html#exr:solve-gause">9.1</a> you will show that <span class="math inline">\(\displaystyle a = \ln \left( \frac{K}{0.45} - 1 \right)\)</span>. Equation <a href="likelihood-09.html#eq:gause-09">(9.8)</a> then has two parameters: <span class="math inline">\(K\)</span> and <span class="math inline">\(b\)</span>. Here we are going to explore the likelihood function to try to determine the best set of values for the two parameters <span class="math inline">\(K\)</span> and <span class="math inline">\(b\)</span> using a function in the <code>demodelr</code> package called <code>compute_likelihood</code>. Inputs to the <code>compute_likelihood</code> function are the following:</p>
<ul>
<li>A function <span class="math inline">\(y=f(x,\vec{\alpha})\)</span></li>
<li>A dataset <span class="math inline">\((\vec{x},\vec{y})\)</span></li>
<li>Ranges of your parameters <span class="math inline">\(\vec{\alpha}\)</span>.</li>
</ul>
<p>The <code>compute_likelihood</code> function also has an optional input <code>logLikely</code> that allows you to specify if you want to compute the likelihood or the log-likelihood. The default is that <code>logLikely</code> is <code>FALSE</code>, meaning that the normal likelihoods are plotted.</p>
<p>First we will define the equation used to compute our model in the likelihood. As with the functions <code>euler</code> or <code>systems</code> in Chapter <a href="euler-04.html#euler-04">4</a> we need to define this function:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="likelihood-09.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(demodelr)</span>
<span id="cb39-2"><a href="likelihood-09.html#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="likelihood-09.html#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the solution to the differential equation with</span></span>
<span id="cb39-4"><a href="likelihood-09.html#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># parameters K and bGause model equation</span></span>
<span id="cb39-5"><a href="likelihood-09.html#cb39-5" aria-hidden="true" tabindex="-1"></a>gause_model <span class="ot">&lt;-</span> volume <span class="sc">~</span> K <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">log</span>(K <span class="sc">/</span> <span class="fl">0.45</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">-</span> b <span class="sc">*</span> time))</span>
<span id="cb39-6"><a href="likelihood-09.html#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="likelihood-09.html#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="likelihood-09.html#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify the ranges of the parameters that we wish to investigate</span></span>
<span id="cb39-9"><a href="likelihood-09.html#cb39-9" aria-hidden="true" tabindex="-1"></a>kParam <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">5</span>, <span class="dv">20</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb39-10"><a href="likelihood-09.html#cb39-10" aria-hidden="true" tabindex="-1"></a>bParam <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb39-11"><a href="likelihood-09.html#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="likelihood-09.html#cb39-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-13"><a href="likelihood-09.html#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Allow for all the possible combinations of parameters</span></span>
<span id="cb39-14"><a href="likelihood-09.html#cb39-14" aria-hidden="true" tabindex="-1"></a>gause_parameters <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">K =</span> kParam, <span class="at">b =</span> bParam)</span>
<span id="cb39-15"><a href="likelihood-09.html#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="likelihood-09.html#cb39-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Now compute the likelihood</span></span>
<span id="cb39-17"><a href="likelihood-09.html#cb39-17" aria-hidden="true" tabindex="-1"></a>gause_likelihood <span class="ot">&lt;-</span> <span class="fu">compute_likelihood</span>(</span>
<span id="cb39-18"><a href="likelihood-09.html#cb39-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> gause_model,</span>
<span id="cb39-19"><a href="likelihood-09.html#cb39-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> yeast,</span>
<span id="cb39-20"><a href="likelihood-09.html#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">parameters =</span> gause_parameters,</span>
<span id="cb39-21"><a href="likelihood-09.html#cb39-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">logLikely =</span> <span class="cn">FALSE</span></span>
<span id="cb39-22"><a href="likelihood-09.html#cb39-22" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>Ok, let’s break this code down step by step:</p>
<ul>
<li>The line <code>gause_model &lt;- volume ~ K/(1+exp(log(k/0.45-1)-b*time))</code> identifies the formula that relates the variables <code>time</code> to <code>volume</code> in the dataset <code>yeast</code>.</li>
<li>We define the ranges (minimum and maximum values) for our parameters by defining a sequence. Because we want to look at <em>all possible combinations</em> of these parameters we use the command <code>expand.grid</code>.</li>
<li>The input <code>logLikely = FALSE</code> to <code>compute_likelihood</code> reports back likelihood values.</li>
</ul>
<p>Some care is needed in defining the number of points (<code>length.out = 100</code>) in the sequence that we want to evaluate - we will have <span class="math inline">\(100^{2}\)</span> different combinations of <span class="math inline">\(K\)</span> and <span class="math inline">\(b\)</span> on our grid, which does take time to evaluate.</p>
<p>The output to <code>compute_likelihood</code> is a list, which is a flexible data structure in <code>R</code>. You can think of this as a collection of items - which could be data frames of different sizes. In this case, what gets returned are two data frames: <code>likelihood</code>, which is a data frame of likelihood values for each of the parameters and <code>opt_value</code>, which reports back the values of the parameters that optimize the likelihood function. Note that the optimum value is <em>an approximation</em>, as it is just the optimum from the input values of <span class="math inline">\(K\)</span> and <span class="math inline">\(b\)</span> provided on our grid. Let’s take a look at the reported optimum values, which we can do with the syntax <code>LIST_NAME$VARIABLE_NAME</code>, where the dollar sign ($) helps identify which variable from the list you are investigating.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="likelihood-09.html#cb40-1" aria-hidden="true" tabindex="-1"></a>gause_likelihood<span class="sc">$</span>opt_value</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##       K     b   l_hood log_lik
##   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;lgl&gt;  
## 1  12.7 0.242 0.000348 FALSE</code></pre>
<p>It is also important to visualize this likelihood function. For this dataset we have the two parameters <span class="math inline">\(K\)</span> and <span class="math inline">\(b\)</span>, so the likelihood function will be a <em>likelihood surface</em>, rather than a two-dimensional plot. To visualize this in <code>R</code> we can use a contour diagram. Figure <a href="likelihood-09.html#fig:gause-likely-plot">9.6</a> displays this countour plot.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="likelihood-09.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the likelihood values</span></span>
<span id="cb42-2"><a href="likelihood-09.html#cb42-2" aria-hidden="true" tabindex="-1"></a>my_likelihood <span class="ot">&lt;-</span> gause_likelihood<span class="sc">$</span>likelihood</span>
<span id="cb42-3"><a href="likelihood-09.html#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="likelihood-09.html#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a contour plot</span></span>
<span id="cb42-5"><a href="likelihood-09.html#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> my_likelihood) <span class="sc">+</span></span>
<span id="cb42-6"><a href="likelihood-09.html#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="fu">aes</span>(<span class="at">x =</span> K, <span class="at">y =</span> b, <span class="at">fill =</span> l_hood)) <span class="sc">+</span></span>
<span id="cb42-7"><a href="likelihood-09.html#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_contour</span>(<span class="fu">aes</span>(<span class="at">x =</span> K, <span class="at">y =</span> b, <span class="at">z =</span> l_hood))</span></code></pre></div>
<div class="figure"><span id="fig:gause-likely-plot"></span>
<img src="explore-model-zobitz-220419_files/figure-html/gause-likely-plot-1.png" alt="Likelihood surface and contour lines for the `yeast` dataset." width="672" />
<p class="caption">
FIGURE 9.6: Likelihood surface and contour lines for the <code>yeast</code> dataset.
</p>
</div>
<p>Similar to before, let’s take this step by step:</p>
<ul>
<li>The command <code>my_likelihood</code> just puts the likelihood values in a data frame.</li>
<li>The <code>ggplot</code> command is similar to that used before.</li>
<li>We use <code>geom_tile</code> to visualize the likelihood surface. There are three required inputs from the <code>my_likelihood</code> data frame: the <code>x</code> and <code>y</code> axis data values and the <code>fill</code> value, which represents the height of the likelihood function.</li>
<li>The command <code>stat_contour</code> draws the contour lines, or places where the likelihood function has the same value. Notice how we used <code>z = l_hood</code> rather than <code>fill</code> here. This function helps “smooth” out any jaggedness in the contours.</li>
</ul>
<p>In Figure <a href="likelihood-09.html#fig:gause-likely-plot">9.6</a> there appears to be a large region where the likelihood has the same value. (Admittedly I chose some broad parameter ranges for <span class="math inline">\(K\)</span> and <span class="math inline">\(b\)</span>). We can refine that by producing a second contour plot that focuses in on parameters closer to the calculated optimum value at <span class="math inline">\(K=13\)</span> and <span class="math inline">\(b=0.07\)</span> (Figure <a href="likelihood-09.html#fig:revised-gause-likelihood">9.7</a>):</p>
<pre><code>## # A tibble: 1 × 4
##       K     b   l_hood log_lik
##   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;lgl&gt;  
## 1  12.8 0.241 0.000349 FALSE</code></pre>
<div class="figure"><span id="fig:revised-gause-likelihood"></span>
<img src="explore-model-zobitz-220419_files/figure-html/revised-gause-likelihood-1.png" alt="Zoomed in likelihood surface. for the `yeast` dataset. The computed location of the optimum value is shown as a red point." width="672" />
<p class="caption">
FIGURE 9.7: Zoomed in likelihood surface. for the <code>yeast</code> dataset. The computed location of the optimum value is shown as a red point.
</p>
</div>
<p>The reported values for <span class="math inline">\(K\)</span> (12.8) and <span class="math inline">\(b\)</span> (0.241) may be close to what was reported from Figure <a href="likelihood-09.html#fig:gause-likely-plot">9.6</a>. Notice that in Figure <a href="likelihood-09.html#fig:revised-gause-likelihood">9.7</a> I also added in the location of the optimum point with <code>geom_point()</code>.</p>
<p>As a final step, once you have settled on the value that optimizes the likelihood function, is to compare the optimized parameters against the data (Figure <a href="likelihood-09.html#fig:gause-model-data-09">9.8</a>):</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="likelihood-09.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the parameters and the times to evaluate:</span></span>
<span id="cb44-2"><a href="likelihood-09.html#cb44-2" aria-hidden="true" tabindex="-1"></a>my_params <span class="ot">&lt;-</span> gause_likelihood_rev<span class="sc">$</span>opt_value</span>
<span id="cb44-3"><a href="likelihood-09.html#cb44-3" aria-hidden="true" tabindex="-1"></a>time <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">60</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb44-4"><a href="likelihood-09.html#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="likelihood-09.html#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the right hand side of your equations</span></span>
<span id="cb44-6"><a href="likelihood-09.html#cb44-6" aria-hidden="true" tabindex="-1"></a>new_eq <span class="ot">&lt;-</span> gause_model <span class="sc">%&gt;%</span></span>
<span id="cb44-7"><a href="likelihood-09.html#cb44-7" aria-hidden="true" tabindex="-1"></a>  formula.tools<span class="sc">::</span><span class="fu">rhs</span>()</span>
<span id="cb44-8"><a href="likelihood-09.html#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="likelihood-09.html#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co"># This collects the parameters and data into a list</span></span>
<span id="cb44-10"><a href="likelihood-09.html#cb44-10" aria-hidden="true" tabindex="-1"></a>in_list <span class="ot">&lt;-</span> <span class="fu">c</span>(my_params, time) <span class="sc">%&gt;%</span> <span class="fu">as.list</span>()</span>
<span id="cb44-11"><a href="likelihood-09.html#cb44-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-12"><a href="likelihood-09.html#cb44-12" aria-hidden="true" tabindex="-1"></a><span class="co"># The eval command evaluates your model</span></span>
<span id="cb44-13"><a href="likelihood-09.html#cb44-13" aria-hidden="true" tabindex="-1"></a>out_model <span class="ot">&lt;-</span> <span class="fu">eval</span>(new_eq, <span class="at">envir =</span> in_list)</span>
<span id="cb44-14"><a href="likelihood-09.html#cb44-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-15"><a href="likelihood-09.html#cb44-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-16"><a href="likelihood-09.html#cb44-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Now collect everything into a data frame:</span></span>
<span id="cb44-17"><a href="likelihood-09.html#cb44-17" aria-hidden="true" tabindex="-1"></a>my_prediction <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">time =</span> time, <span class="at">volume =</span> out_model)</span>
<span id="cb44-18"><a href="likelihood-09.html#cb44-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-19"><a href="likelihood-09.html#cb44-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-20"><a href="likelihood-09.html#cb44-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb44-21"><a href="likelihood-09.html#cb44-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb44-22"><a href="likelihood-09.html#cb44-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> yeast,</span>
<span id="cb44-23"><a href="likelihood-09.html#cb44-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> volume),</span>
<span id="cb44-24"><a href="likelihood-09.html#cb44-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb44-25"><a href="likelihood-09.html#cb44-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">2</span></span>
<span id="cb44-26"><a href="likelihood-09.html#cb44-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb44-27"><a href="likelihood-09.html#cb44-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(</span>
<span id="cb44-28"><a href="likelihood-09.html#cb44-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> my_prediction,</span>
<span id="cb44-29"><a href="likelihood-09.html#cb44-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> volume)</span>
<span id="cb44-30"><a href="likelihood-09.html#cb44-30" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb44-31"><a href="likelihood-09.html#cb44-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Volume&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:gause-model-data-09"></span>
<img src="explore-model-zobitz-220419_files/figure-html/gause-model-data-09-1.png" alt="Model and data comparison of the `yeast` dataset from maximum likelihood estimation." width="672" />
<p class="caption">
FIGURE 9.8: Model and data comparison of the <code>yeast</code> dataset from maximum likelihood estimation.
</p>
</div>
<p>All right, this code block has some new commands and techniques that need explaining. Once we have the parameter estimates we need to compute the modeled values.</p>
<ul>
<li>First we define the <code>params</code> and the <code>time</code> we wish to evaluate with our model.</li>
<li>We need to evaluate the right hand side of <span class="math inline">\(\displaystyle y = \frac{K}{1+e^{a+bt}}\)</span>, so the definition of <code>new_eq</code> helps to do that, using the package <code>formula.tools</code>.</li>
<li>The <code>%&gt;%</code> is the <code>tidyverse</code> <a href="https://r4ds.had.co.nz/pipes.html#pipes">pipe</a>. This is a very useful command to help make code more readable!</li>
<li><code>in_list &lt;- c(params,my_time) %&gt;% as.list()</code> collects the parameters and input times in one list to evaluate the model with <code>out_model &lt;- eval(new_eq,envir=in_list)</code></li>
<li>We make a data frame called <code>my_prediction</code> so we can then plot.</li>
</ul>
<p>And the rest of the plotting commands you should be used to. This activity focused on the likelihood function - Exercise <a href="likelihood-09.html#exr:log-likelihood-yeast">9.3</a> has you repeat this analysis with the log-likelihood function.</p>
</div>
<div id="looking-back-and-forward" class="section level2 hasAnchor" number="9.5">
<h2><span class="header-section-number">9.5</span> Looking back and forward<a href="likelihood-09.html#looking-back-and-forward" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This chapter covered a lot of ground - from probability and likelihood functions to computing and visualizing these. A good strategy for a likelihood function is to visualize the function and then explore to find values that optimize the likelihood or log-likelihood function. This approach is one example of <em>successive approximations</em> or using an iterative method to determine a solution. While this chapter focused on optimizing a likelihood function with one or two parameters, the successive approximation method does generalize to more parameters. However searching for parameters becomes tricky (read: tedious and slow) in high-dimensional spaces. In later chapters we will explore numerical methods to accelerate convergence to an optimum value.</p>
</div>
<div id="exercises-8" class="section level2 hasAnchor" number="9.6">
<h2><span class="header-section-number">9.6</span> Exercises<a href="likelihood-09.html#exercises-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>

<div class="exercise">
<span id="exr:solve-gause" class="exercise"><strong>Exercise 9.1  </strong></span>Algebraically solve the equation <span class="math inline">\(\displaystyle 0.45 = \frac{K}{1+e^{a}}\)</span> for <span class="math inline">\(a\)</span>.
</div>

<div class="exercise">
<span id="exr:show-small-likely" class="exercise"><strong>Exercise 9.2  </strong></span>Compute the values of <span class="math inline">\(L(b|\vec{x},\vec{y})\)</span> and <span class="math inline">\(\ln(L(b|\vec{x},\vec{y}))\)</span> for each of the data points in Equation <a href="likelihood-09.html#eq:small-data-likely">(9.6)</a> when <span class="math inline">\(b=1.865\)</span> and <span class="math inline">\(\sigma=1\)</span>. (This means that these 4 values would be multiplied or added when you compute the full likelihood function.) Explain if the likelihood or log-likelihood would be easier to calculate in instances when the number of observations is large.
</div>

<div class="exercise">
<span id="exr:log-likelihood-yeast" class="exercise"><strong>Exercise 9.3  </strong></span>Visualize the likelihood function for the <code>yeast</code> dataset, but in this case report out and visualize the log-likelihood. (This means that you are setting the option <code>logLikely = TRUE</code> in the <code>compute_likelihood</code> function.) Compare the log-likelihood surface to Figure <a href="likelihood-09.html#fig:revised-gause-likelihood">9.7</a>.
</div>

<div class="exercise">
<p><span id="exr:small-data-invest" class="exercise"><strong>Exercise 9.4  </strong></span>When we generated our plot of the likelihood function in Figure <a href="likelihood-09.html#fig:small-likelihood-plot">9.3</a> we assumed that <span class="math inline">\(\sigma=1\)</span> in Equation (9.6). For this exercise you will explore what happens in Equation (9.6) as <span class="math inline">\(\sigma\)</span> increases or decreases.</p>
<ol style="list-style-type: lower-alpha">
<li>Use desmos () or <code>R</code> to generate a plot of Equation <a href="likelihood-09.html#eq:small-data-likely">(9.6)</a>. What happens to the shape of the likelihood function as <span class="math inline">\(\sigma\)</span> increases?</li>
<li>How does the estimate of <span class="math inline">\(b\)</span> change as <span class="math inline">\(\sigma\)</span> changes?</li>
<li>The spread of the distribution (in terms of it being more peaked or less peaked) is a measure of uncertainty of a parameter estimate. How does the resulting parameter uncertainty change as <span class="math inline">\(\sigma\)</span> changes?</li>
</ol>
</div>

<div class="exercise">
<p><span id="exr:small-data-optimize" class="exercise"><strong>Exercise 9.5  </strong></span>Using Equation <a href="likelihood-09.html#eq:small-data-likely">(9.6)</a> with <span class="math inline">\(\sigma = 1\)</span>:</p>
<ol style="list-style-type: lower-alpha">
<li><p>Apply the natural logarithm to both sides of this expression. Using properties of logarithms, show that the log-likelihood function is <span class="math inline">\(\displaystyle \ln(L(b)) =-2 \ln(2) - 2 \ln (\pi) -\frac{(3-b)^{2}}{2}-\frac{(5-2b)^{2}}{2}-\frac{(4-4b)^{2}}{2}-\frac{(10-4b)^{2}}{2}\)</span>.</p></li>
<li><p>Make a plot of the log-likelihood function (in desmos or <code>R</code>).</p></li>
<li><p>At what values of <span class="math inline">\(b\)</span> Where is this function optimized? Does your graph indicate that it is a maximum or a minimum value?</p></li>
<li><p>Compare this likelihood estimate for <span class="math inline">\(b\)</span> to what was found in Figure <a href="likelihood-09.html#fig:small-likelihood-plot">9.3</a>.</p></li>
</ol>
</div>

<div class="exercise">
<p><span id="exr:full-linear" class="exercise"><strong>Exercise 9.6  </strong></span>Consider the linear model <span class="math inline">\(y=a+bx\)</span> for the following dataset:</p>
<table>
<thead>
<tr class="header">
<th align="center"><em>x</em></th>
<th align="center"><em>y</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">5</td>
</tr>
<tr class="odd">
<td align="center">4</td>
<td align="center">4</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">10</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li>With the function <code>compute_likelihood</code>, generate a contour plot of both the likelihood and log-likelihood functions. You may assume <span class="math inline">\(0 \leq a \leq 5\)</span> and <span class="math inline">\(0 \leq b \leq 5\)</span>.</li>
<li>Make a scatterplot of these data with the equation <span class="math inline">\(y=a+bx\)</span> with your maximum likelihood parameter estimates.</li>
<li>Earlier when we fit <span class="math inline">\(y=bx\)</span> we found <span class="math inline">\(b=1.865\)</span>. How does adding <span class="math inline">\(a\)</span> as a model parameter affect your estimate of <span class="math inline">\(b\)</span>?</li>
</ol>
</div>

<div class="exercise">
<span id="exr:unnamed-chunk-130" class="exercise"><strong>Exercise 9.7  </strong></span>For the function <span class="math inline">\(\displaystyle P(t)=\frac{K}{1+e^{a+bt}}\)</span>, with <span class="math inline">\(P(0)=P_{0}\)</span>, determine an expression for the parameter <span class="math inline">\(a\)</span> in terms of <span class="math inline">\(K\)</span>, <span class="math inline">\(b\)</span>, and <span class="math inline">\(P_{0}\)</span>.
</div>

<div class="exercise">
<p><span id="exr:unnamed-chunk-131" class="exercise"><strong>Exercise 9.8  </strong></span>The values returned by the maximum likelihood estimate for Equation <a href="likelihood-09.html#eq:gause-09">(9.8)</a> were a little different from those reported in <span class="citation"><a href="#ref-gause_experimental_1932" role="doc-biblioref">Gause</a> (<a href="#ref-gause_experimental_1932" role="doc-biblioref">1932</a>)</span>:</p>
<table>
<thead>
<tr class="header">
<th align="center"><strong>Parameter</strong></th>
<th align="center"><strong>Maximum Likelihood Estimate</strong></th>
<th align="center"><strong><span class="citation"><a href="#ref-gause_experimental_1932" role="doc-biblioref">Gause</a> (<a href="#ref-gause_experimental_1932" role="doc-biblioref">1932</a>)</span></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(K\)</span></td>
<td align="center">12.7</td>
<td align="center">13.0</td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(b\)</span></td>
<td align="center">0.24242</td>
<td align="center">0.21827</td>
</tr>
</tbody>
</table>
Using the <code>yeast</code> dataset, plot the function <span class="math inline">\(\displaystyle y = \frac{K}{1+e^{a-bt}}\)</span> (setting <span class="math inline">\(\displaystyle a = \ln \left( \frac{K}{0.45} - 1 \right)\)</span>) using both sets of parameters. Which approach (the Maximum Likelihood estimate or <span class="citation"><a href="#ref-gause_experimental_1932" role="doc-biblioref">Gause</a> (<a href="#ref-gause_experimental_1932" role="doc-biblioref">1932</a>)</span>) does a better job representing the data?
</div>

<div class="exercise">
<p><span id="exr:unnamed-chunk-132" class="exercise"><strong>Exercise 9.9  </strong></span>An equation that relates a consumer’s nutrient content (denoted as <span class="math inline">\(y\)</span>) to the nutrient content of food (denoted as <span class="math inline">\(x\)</span>) is given by: <span class="math inline">\(\displaystyle y = c x^{1/\theta}\)</span>, where <span class="math inline">\(\theta \geq 1\)</span> and <span class="math inline">\(c&gt;0\)</span> are both constants.</p>
<ol style="list-style-type: lower-alpha">
<li>Use the dataset <code>phosphorous</code> to make a scatterplot with the variable <code>algae</code> on the horizontal axis, <code>daphnia</code> on the vertical axis.</li>
<li>Generate a contour plot for the likelihood function for these data. You may assume <span class="math inline">\(0 \leq c \leq 5\)</span> and <span class="math inline">\(1 \leq \theta \leq 20\)</span>. What are the values of <span class="math inline">\(c\)</span> and <span class="math inline">\(\theta\)</span> that optimize the likelihood? <em>Hint:</em> for the dataset <code>phosphorous</code> be sure to use the variables <span class="math inline">\(x=\)</span><code>algae</code> and <span class="math inline">\(y=\)</span><code>daphnia</code>.</li>
<li>Add the fitted curve to your scatterplot and evaluate your fitted results.</li>
</ol>
</div>

<div class="exercise">
<p><span id="exr:unnamed-chunk-133" class="exercise"><strong>Exercise 9.10  </strong></span>A dog’s weight <span class="math inline">\(W\)</span> (pounds) changes over <span class="math inline">\(D\)</span> days according to the following function:</p>
<p><span class="math display">\[\begin{equation}
W =f(D,p_{1},p_{2})= \frac{p_{1}}{1+e^{2.462-p_{2}D}},
\end{equation}\]</span></p>
<p>where <span class="math inline">\(p_{1}\)</span> and <span class="math inline">\(p_{2}\)</span> are parameters.</p>
<ol style="list-style-type: lower-alpha">
<li>This function can be used to describe the data <code>wilson</code>. Make a scatterplot with the <code>wilson</code> data. What is the long term weight of the dog?</li>
<li>Generate a contour plot for the likelihood function for these data. What are the values of <span class="math inline">\(p_{1}\)</span> and <span class="math inline">\(p_{2}\)</span> that optimize the likelihood? <em>You may assume that <span class="math inline">\(p_{1}\)</span> and <span class="math inline">\(p_{2}\)</span> are both positive.</em></li>
<li>With your values of <span class="math inline">\(p_{1}\)</span> and <span class="math inline">\(p_{2}\)</span> add the function <span class="math inline">\(W\)</span> to your scatterplot and compare the fitted curve to the data.</li>
</ol>
</div>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-devore_modern_2021" class="csl-entry">
Devore, Jay L., Kenneth N. Berk, and Matthew A. Carlton. 2021. <em>Modern <span>Mathematical Statistics</span> with <span>Applications</span></em>. 3rd ed. Springer <span>Texts</span> in <span>Statistics</span>. Cham, Switzerland: <span>Springer International Publishing</span>. <a href="https://doi.org/10.1007/978-3-030-55156-8">https://doi.org/10.1007/978-3-030-55156-8</a>.
</div>
<div id="ref-gause_experimental_1932" class="csl-entry">
Gause, G. F. 1932. <span>“Experimental <span>Studies</span> on the <span>Struggle</span> for <span>Existence</span>: <span>I</span>. <span>Mixed Population</span> of <span>Two Species</span> of <span>Yeast</span>.”</span> <em>Journal of Experimental Biology</em> 9 (4): 389–402.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="28">
<li id="fn28"><p>See <span class="citation"><a href="#ref-devore_modern_2021" role="doc-biblioref">Devore, Berk, and Carlton</a> (<a href="#ref-devore_modern_2021" role="doc-biblioref">2021</a>)</span> for a more refined definition of probability.<a href="likelihood-09.html#fnref28" class="footnote-back">↩︎</a></p></li>
<li id="fn29"><p>Were you ever asked to find the antiderivative of <span class="math inline">\(\displaystyle \int e^{-x^{2}} \; dx\)</span>? You may recall that there is easy antiderivative - and to find values of definite integrals you need to approximate numerically. Thankfully <code>R</code> does that work using sophisticated numerical integration techniques!<a href="likelihood-09.html#fnref29" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="linear-regression-08.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cost-fns-10.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jules32/bookdown-tutorial/edit/master/09-likelihood.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://jmzobitz.github.io/ModelingWithR/09-likelihood.Rmd",
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
