<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 22 Simulating and Visualizing Randomness | Exploring Modeling with Data and Differential Equations Using R</title>
  <meta name="description" content="A textbook used for combining differential equation models with data using R." />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 22 Simulating and Visualizing Randomness | Exploring Modeling with Data and Differential Equations Using R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="A textbook used for combining differential equation models with data using R." />
  <meta name="github-repo" content="openscapes/series" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 22 Simulating and Visualizing Randomness | Exploring Modeling with Data and Differential Equations Using R" />
  
  <meta name="twitter:description" content="A textbook used for combining differential equation models with data using R." />
  

<meta name="author" content="John M. Zobitz" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="stoch-sys-21.html"/>
<link rel="next" href="random-walks-23.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="lib/css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="lib/css/style.css" type="text/css" />
<link rel="stylesheet" href="lib/css/lesson.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>Modeling with Data and Differential Equations in R</strong><br>by John Zobitz</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#computational-code"><i class="fa fa-check"></i>Computational code</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#questions-comments-issues"><i class="fa fa-check"></i>Questions? Comments? Issues?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-cover"><i class="fa fa-check"></i>About the cover</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="part"><span><b>I Models with Differential Equations</b></span></li>
<li class="chapter" data-level="1" data-path="intro-01.html"><a href="intro-01.html"><i class="fa fa-check"></i><b>1</b> Models of Rates with Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro-01.html"><a href="intro-01.html#rates-of-change-in-the-world-a-model-is-born"><i class="fa fa-check"></i><b>1.1</b> Rates of change in the world: a model is born</a></li>
<li class="chapter" data-level="1.2" data-path="intro-01.html"><a href="intro-01.html#modeling-in-context-the-spread-of-a-disease"><i class="fa fa-check"></i><b>1.2</b> Modeling in context: the spread of a disease</a></li>
<li class="chapter" data-level="1.3" data-path="intro-01.html"><a href="intro-01.html#model-solutions"><i class="fa fa-check"></i><b>1.3</b> Model solutions</a></li>
<li class="chapter" data-level="1.4" data-path="intro-01.html"><a href="intro-01.html#which-model-is-best"><i class="fa fa-check"></i><b>1.4</b> Which model is best?</a></li>
<li class="chapter" data-level="1.5" data-path="intro-01.html"><a href="intro-01.html#start-here"><i class="fa fa-check"></i><b>1.5</b> Start here</a></li>
<li class="chapter" data-level="1.6" data-path="intro-01.html"><a href="intro-01.html#exercises"><i class="fa fa-check"></i><b>1.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-intro-02.html"><a href="r-intro-02.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-intro-02.html"><a href="r-intro-02.html#r-and-rstudio"><i class="fa fa-check"></i><b>2.1</b> <code>R</code> and RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="r-intro-02.html"><a href="r-intro-02.html#first-steps-getting-acquainted-with-r"><i class="fa fa-check"></i><b>2.2</b> First steps: getting acquainted with <code>R</code></a></li>
<li class="chapter" data-level="2.3" data-path="r-intro-02.html"><a href="r-intro-02.html#increasing-functionality-with-packages"><i class="fa fa-check"></i><b>2.3</b> Increasing functionality with packages</a></li>
<li class="chapter" data-level="2.4" data-path="r-intro-02.html"><a href="r-intro-02.html#working-with-r-variables-data-frames-and-datasets"><i class="fa fa-check"></i><b>2.4</b> Working with <code>R</code>: variables, data frames, and datasets</a></li>
<li class="chapter" data-level="2.5" data-path="r-intro-02.html"><a href="r-intro-02.html#visualization-with-r"><i class="fa fa-check"></i><b>2.5</b> Visualization with <code>R</code></a></li>
<li class="chapter" data-level="2.6" data-path="r-intro-02.html"><a href="r-intro-02.html#defining-functions"><i class="fa fa-check"></i><b>2.6</b> Defining functions</a></li>
<li class="chapter" data-level="2.7" data-path="r-intro-02.html"><a href="r-intro-02.html#concluding-thoughts"><i class="fa fa-check"></i><b>2.7</b> Concluding thoughts</a></li>
<li class="chapter" data-level="2.8" data-path="r-intro-02.html"><a href="r-intro-02.html#exercises-1"><i class="fa fa-check"></i><b>2.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html"><i class="fa fa-check"></i><b>3</b> Modeling with Rates of Change</a>
<ul>
<li class="chapter" data-level="3.1" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html#competing-plant-species-and-equilibrium-solutions"><i class="fa fa-check"></i><b>3.1</b> Competing plant species and equilibrium solutions</a></li>
<li class="chapter" data-level="3.2" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html#the-law-of-mass-action"><i class="fa fa-check"></i><b>3.2</b> The Law of Mass Action</a></li>
<li class="chapter" data-level="3.3" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html#coupled-differential-equations-lynx-and-hares"><i class="fa fa-check"></i><b>3.3</b> Coupled differential equations: lynx and hares</a></li>
<li class="chapter" data-level="3.4" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html#functional-responses"><i class="fa fa-check"></i><b>3.4</b> Functional responses</a></li>
<li class="chapter" data-level="3.5" data-path="modeling-rates-03.html"><a href="modeling-rates-03.html#exercises-2"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="euler-04.html"><a href="euler-04.html"><i class="fa fa-check"></i><b>4</b> Euler’s Method</a>
<ul>
<li class="chapter" data-level="4.1" data-path="euler-04.html"><a href="euler-04.html#the-flu-and-locally-linear-approximation"><i class="fa fa-check"></i><b>4.1</b> The flu and locally linear approximation</a></li>
<li class="chapter" data-level="4.2" data-path="euler-04.html"><a href="euler-04.html#a-workflow-for-approximation"><i class="fa fa-check"></i><b>4.2</b> A workflow for approximation</a></li>
<li class="chapter" data-level="4.3" data-path="euler-04.html"><a href="euler-04.html#building-an-iterative-method"><i class="fa fa-check"></i><b>4.3</b> Building an iterative method</a></li>
<li class="chapter" data-level="4.4" data-path="euler-04.html"><a href="euler-04.html#eulers-method-and-beyond"><i class="fa fa-check"></i><b>4.4</b> Euler’s method and beyond</a></li>
<li class="chapter" data-level="4.5" data-path="euler-04.html"><a href="euler-04.html#exercises-3"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="phase-05.html"><a href="phase-05.html"><i class="fa fa-check"></i><b>5</b> Phase Lines and Equilibrium Solutions</a>
<ul>
<li class="chapter" data-level="5.1" data-path="phase-05.html"><a href="phase-05.html#equilibrium-solutions"><i class="fa fa-check"></i><b>5.1</b> Equilibrium solutions</a></li>
<li class="chapter" data-level="5.2" data-path="phase-05.html"><a href="phase-05.html#phase-lines-for-differential-equations"><i class="fa fa-check"></i><b>5.2</b> Phase lines for differential equations</a></li>
<li class="chapter" data-level="5.3" data-path="phase-05.html"><a href="phase-05.html#a-stability-test-for-equilibrium-solutions"><i class="fa fa-check"></i><b>5.3</b> A stability test for equilibrium solutions</a></li>
<li class="chapter" data-level="5.4" data-path="phase-05.html"><a href="phase-05.html#exercises-4"><i class="fa fa-check"></i><b>5.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="coupled-06.html"><a href="coupled-06.html"><i class="fa fa-check"></i><b>6</b> Coupled Systems of Equations</a>
<ul>
<li class="chapter" data-level="6.1" data-path="coupled-06.html"><a href="coupled-06.html#flu-with-quarantine-and-equilibrium-solutions"><i class="fa fa-check"></i><b>6.1</b> Flu with quarantine and equilibrium solutions</a></li>
<li class="chapter" data-level="6.2" data-path="coupled-06.html"><a href="coupled-06.html#nullclines"><i class="fa fa-check"></i><b>6.2</b> Nullclines</a></li>
<li class="chapter" data-level="6.3" data-path="coupled-06.html"><a href="coupled-06.html#phase-planes"><i class="fa fa-check"></i><b>6.3</b> Phase planes</a></li>
<li class="chapter" data-level="6.4" data-path="coupled-06.html"><a href="coupled-06.html#generating-a-phase-plane-in-r"><i class="fa fa-check"></i><b>6.4</b> Generating a phase plane in <code>R</code></a></li>
<li class="chapter" data-level="6.5" data-path="coupled-06.html"><a href="coupled-06.html#slope-fields"><i class="fa fa-check"></i><b>6.5</b> Slope fields</a></li>
<li class="chapter" data-level="6.6" data-path="coupled-06.html"><a href="coupled-06.html#exercises-5"><i class="fa fa-check"></i><b>6.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="exact-solns-07.html"><a href="exact-solns-07.html"><i class="fa fa-check"></i><b>7</b> Exact Solutions to Differential Equations</a>
<ul>
<li class="chapter" data-level="7.1" data-path="exact-solns-07.html"><a href="exact-solns-07.html#verify-a-solution"><i class="fa fa-check"></i><b>7.1</b> Verify a solution</a></li>
<li class="chapter" data-level="7.2" data-path="exact-solns-07.html"><a href="exact-solns-07.html#separable-differential-equations"><i class="fa fa-check"></i><b>7.2</b> Separable differential equations</a></li>
<li class="chapter" data-level="7.3" data-path="exact-solns-07.html"><a href="exact-solns-07.html#integrating-factors"><i class="fa fa-check"></i><b>7.3</b> Integrating factors</a></li>
<li class="chapter" data-level="7.4" data-path="exact-solns-07.html"><a href="exact-solns-07.html#verify-broad-07"><i class="fa fa-check"></i><b>7.4</b> Applying the verification method to coupled equations</a></li>
<li class="chapter" data-level="7.5" data-path="exact-solns-07.html"><a href="exact-solns-07.html#exercises-6"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>II Parameterizing Models with Data</b></span></li>
<li class="chapter" data-level="8" data-path="linear-regression-08.html"><a href="linear-regression-08.html"><i class="fa fa-check"></i><b>8</b> Linear Regression and Curve Fitting</a>
<ul>
<li class="chapter" data-level="8.1" data-path="linear-regression-08.html"><a href="linear-regression-08.html#what-is-parameter-estimation"><i class="fa fa-check"></i><b>8.1</b> What is parameter estimation?</a></li>
<li class="chapter" data-level="8.2" data-path="linear-regression-08.html"><a href="linear-regression-08.html#parameter-estimation-for-global-temperature-data"><i class="fa fa-check"></i><b>8.2</b> Parameter estimation for global temperature data</a></li>
<li class="chapter" data-level="8.3" data-path="linear-regression-08.html"><a href="linear-regression-08.html#beyond-linear-08"><i class="fa fa-check"></i><b>8.3</b> Moving beyond linear models for parameter estimation</a></li>
<li class="chapter" data-level="8.4" data-path="linear-regression-08.html"><a href="linear-regression-08.html#parameter-estimation-with-nonlinear-models"><i class="fa fa-check"></i><b>8.4</b> Parameter estimation with nonlinear models</a></li>
<li class="chapter" data-level="8.5" data-path="linear-regression-08.html"><a href="linear-regression-08.html#towards-model-data-fusion"><i class="fa fa-check"></i><b>8.5</b> Towards model-data fusion</a></li>
<li class="chapter" data-level="8.6" data-path="linear-regression-08.html"><a href="linear-regression-08.html#exercises-7"><i class="fa fa-check"></i><b>8.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="likelihood-09.html"><a href="likelihood-09.html"><i class="fa fa-check"></i><b>9</b> Probability and Likelihood Functions</a>
<ul>
<li class="chapter" data-level="9.1" data-path="likelihood-09.html"><a href="likelihood-09.html#linear-regression-on-a-small-dataset"><i class="fa fa-check"></i><b>9.1</b> Linear regression on a small dataset</a></li>
<li class="chapter" data-level="9.2" data-path="likelihood-09.html"><a href="likelihood-09.html#continuous-probability-density-functions"><i class="fa fa-check"></i><b>9.2</b> Continuous probability density functions</a></li>
<li class="chapter" data-level="9.3" data-path="likelihood-09.html"><a href="likelihood-09.html#connecting-probabilities-to-linear-regression"><i class="fa fa-check"></i><b>9.3</b> Connecting probabilities to linear regression</a></li>
<li class="chapter" data-level="9.4" data-path="likelihood-09.html"><a href="likelihood-09.html#visualizing-likelihood-surfaces"><i class="fa fa-check"></i><b>9.4</b> Visualizing likelihood surfaces</a></li>
<li class="chapter" data-level="9.5" data-path="likelihood-09.html"><a href="likelihood-09.html#looking-back-and-forward"><i class="fa fa-check"></i><b>9.5</b> Looking back and forward</a></li>
<li class="chapter" data-level="9.6" data-path="likelihood-09.html"><a href="likelihood-09.html#exercises-8"><i class="fa fa-check"></i><b>9.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="cost-fns-10.html"><a href="cost-fns-10.html"><i class="fa fa-check"></i><b>10</b> Cost Functions and Bayes’ Rule</a>
<ul>
<li class="chapter" data-level="10.1" data-path="cost-fns-10.html"><a href="cost-fns-10.html#cost-functions-and-model-data-residuals"><i class="fa fa-check"></i><b>10.1</b> Cost functions and model-data residuals</a></li>
<li class="chapter" data-level="10.2" data-path="cost-fns-10.html"><a href="cost-fns-10.html#further-extensions-to-the-cost-function"><i class="fa fa-check"></i><b>10.2</b> Further extensions to the cost function</a></li>
<li class="chapter" data-level="10.3" data-path="cost-fns-10.html"><a href="cost-fns-10.html#conditional-probabilities-and-bayes-rule"><i class="fa fa-check"></i><b>10.3</b> Conditional probabilities and Bayes’ rule</a></li>
<li class="chapter" data-level="10.4" data-path="cost-fns-10.html"><a href="cost-fns-10.html#bayes-rule-in-action"><i class="fa fa-check"></i><b>10.4</b> Bayes’ rule in action</a></li>
<li class="chapter" data-level="10.5" data-path="cost-fns-10.html"><a href="cost-fns-10.html#next-steps"><i class="fa fa-check"></i><b>10.5</b> Next steps</a></li>
<li class="chapter" data-level="10.6" data-path="cost-fns-10.html"><a href="cost-fns-10.html#exercises-9"><i class="fa fa-check"></i><b>10.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="bootstrap-11.html"><a href="bootstrap-11.html"><i class="fa fa-check"></i><b>11</b> Sampling Distributions and the Bootstrap Method</a>
<ul>
<li class="chapter" data-level="11.1" data-path="bootstrap-11.html"><a href="bootstrap-11.html#histograms-and-their-visualization"><i class="fa fa-check"></i><b>11.1</b> Histograms and their visualization</a></li>
<li class="chapter" data-level="11.2" data-path="bootstrap-11.html"><a href="bootstrap-11.html#statistical-theory-sampling-distributions"><i class="fa fa-check"></i><b>11.2</b> Statistical theory: sampling distributions</a></li>
<li class="chapter" data-level="11.3" data-path="bootstrap-11.html"><a href="bootstrap-11.html#summary-and-next-steps"><i class="fa fa-check"></i><b>11.3</b> Summary and next steps</a></li>
<li class="chapter" data-level="11.4" data-path="bootstrap-11.html"><a href="bootstrap-11.html#exercises-10"><i class="fa fa-check"></i><b>11.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="metropolis-12.html"><a href="metropolis-12.html"><i class="fa fa-check"></i><b>12</b> The Metropolis-Hastings Algorithm</a>
<ul>
<li class="chapter" data-level="12.1" data-path="metropolis-12.html"><a href="metropolis-12.html#estimating-the-growth-of-a-dog"><i class="fa fa-check"></i><b>12.1</b> Estimating the growth of a dog</a></li>
<li class="chapter" data-level="12.2" data-path="metropolis-12.html"><a href="metropolis-12.html#lr-12"><i class="fa fa-check"></i><b>12.2</b> Likelihood ratios for parameter estimation</a></li>
<li class="chapter" data-level="12.3" data-path="metropolis-12.html"><a href="metropolis-12.html#the-metropolis-hastings-algorithm-for-parameter-estimation"><i class="fa fa-check"></i><b>12.3</b> The Metropolis-Hastings algorithm for parameter estimation</a></li>
<li class="chapter" data-level="12.4" data-path="metropolis-12.html"><a href="metropolis-12.html#exercises-11"><i class="fa fa-check"></i><b>12.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="mcmc-13.html"><a href="mcmc-13.html"><i class="fa fa-check"></i><b>13</b> Markov Chain Monte Carlo Parameter Estimation</a>
<ul>
<li class="chapter" data-level="13.1" data-path="mcmc-13.html"><a href="mcmc-13.html#the-recipe-for-mcmc"><i class="fa fa-check"></i><b>13.1</b> The recipe for MCMC</a></li>
<li class="chapter" data-level="13.2" data-path="mcmc-13.html"><a href="mcmc-13.html#mcmc-parameter-estimation-with-an-empirical-model"><i class="fa fa-check"></i><b>13.2</b> MCMC parameter estimation with an empirical model</a></li>
<li class="chapter" data-level="13.3" data-path="mcmc-13.html"><a href="mcmc-13.html#mcmc-parameter-estimation-with-a-differential-equation-model"><i class="fa fa-check"></i><b>13.3</b> MCMC parameter estimation with a differential equation model</a></li>
<li class="chapter" data-level="13.4" data-path="mcmc-13.html"><a href="mcmc-13.html#timing-your-code"><i class="fa fa-check"></i><b>13.4</b> Timing your code</a></li>
<li class="chapter" data-level="13.5" data-path="mcmc-13.html"><a href="mcmc-13.html#further-extensions-to-mcmc"><i class="fa fa-check"></i><b>13.5</b> Further extensions to MCMC</a></li>
<li class="chapter" data-level="13.6" data-path="mcmc-13.html"><a href="mcmc-13.html#exercises-12"><i class="fa fa-check"></i><b>13.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="information-criteria-14.html"><a href="information-criteria-14.html"><i class="fa fa-check"></i><b>14</b> Information Criteria</a>
<ul>
<li class="chapter" data-level="14.1" data-path="information-criteria-14.html"><a href="information-criteria-14.html#model-assessment-guidelines"><i class="fa fa-check"></i><b>14.1</b> Model assessment guidelines</a></li>
<li class="chapter" data-level="14.2" data-path="information-criteria-14.html"><a href="information-criteria-14.html#information-criteria-for-assessing-competing-models"><i class="fa fa-check"></i><b>14.2</b> Information criteria for assessing competing models</a></li>
<li class="chapter" data-level="14.3" data-path="information-criteria-14.html"><a href="information-criteria-14.html#a-few-cautionary-notes"><i class="fa fa-check"></i><b>14.3</b> A few cautionary notes</a></li>
<li class="chapter" data-level="14.4" data-path="information-criteria-14.html"><a href="information-criteria-14.html#exercises-13"><i class="fa fa-check"></i><b>14.4</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>III Stability Analysis for Differential Equations</b></span></li>
<li class="chapter" data-level="15" data-path="linearsystems-15.html"><a href="linearsystems-15.html"><i class="fa fa-check"></i><b>15</b> Systems of Linear Differential Equations</a>
<ul>
<li class="chapter" data-level="15.1" data-path="linearsystems-15.html"><a href="linearsystems-15.html#linear-systems-of-differential-equations-and-matrix-notation"><i class="fa fa-check"></i><b>15.1</b> Linear systems of differential equations and matrix notation</a></li>
<li class="chapter" data-level="15.2" data-path="linearsystems-15.html"><a href="linearsystems-15.html#equilibrium-solutions-1"><i class="fa fa-check"></i><b>15.2</b> Equilibrium solutions</a></li>
<li class="chapter" data-level="15.3" data-path="linearsystems-15.html"><a href="linearsystems-15.html#the-phase-plane"><i class="fa fa-check"></i><b>15.3</b> The phase plane</a></li>
<li class="chapter" data-level="15.4" data-path="linearsystems-15.html"><a href="linearsystems-15.html#non-equilibrium-solutions-and-their-stability"><i class="fa fa-check"></i><b>15.4</b> Non-equilibrium solutions and their stability</a></li>
<li class="chapter" data-level="15.5" data-path="linearsystems-15.html"><a href="linearsystems-15.html#exercises-14"><i class="fa fa-check"></i><b>15.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="nonlinear-16.html"><a href="nonlinear-16.html"><i class="fa fa-check"></i><b>16</b> Systems of Nonlinear Differential Equations</a>
<ul>
<li class="chapter" data-level="16.1" data-path="nonlinear-16.html"><a href="nonlinear-16.html#introducing-nonlinear-systems-of-differential-equations"><i class="fa fa-check"></i><b>16.1</b> Introducing nonlinear systems of differential equations</a></li>
<li class="chapter" data-level="16.2" data-path="nonlinear-16.html"><a href="nonlinear-16.html#zooming-in-on-the-phase-plane"><i class="fa fa-check"></i><b>16.2</b> Zooming in on the phase plane</a></li>
<li class="chapter" data-level="16.3" data-path="nonlinear-16.html"><a href="nonlinear-16.html#determining-equilibrium-solutions-with-nullclines"><i class="fa fa-check"></i><b>16.3</b> Determining equilibrium solutions with nullclines</a></li>
<li class="chapter" data-level="16.4" data-path="nonlinear-16.html"><a href="nonlinear-16.html#stability-of-an-equilibrium-solution"><i class="fa fa-check"></i><b>16.4</b> Stability of an equilibrium solution</a></li>
<li class="chapter" data-level="16.5" data-path="nonlinear-16.html"><a href="nonlinear-16.html#graphing-nullclines-in-a-phase-plane"><i class="fa fa-check"></i><b>16.5</b> Graphing nullclines in a phase plane</a></li>
<li class="chapter" data-level="16.6" data-path="nonlinear-16.html"><a href="nonlinear-16.html#exercises-15"><i class="fa fa-check"></i><b>16.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="jacobian-17.html"><a href="jacobian-17.html"><i class="fa fa-check"></i><b>17</b> Local Linearization and the Jacobian</a>
<ul>
<li class="chapter" data-level="17.1" data-path="jacobian-17.html"><a href="jacobian-17.html#competing-populations"><i class="fa fa-check"></i><b>17.1</b> Competing populations</a></li>
<li class="chapter" data-level="17.2" data-path="jacobian-17.html"><a href="jacobian-17.html#tangent-plane-approximations"><i class="fa fa-check"></i><b>17.2</b> Tangent plane approximations</a></li>
<li class="chapter" data-level="17.3" data-path="jacobian-17.html"><a href="jacobian-17.html#the-jacobian-matrix"><i class="fa fa-check"></i><b>17.3</b> The Jacobian matrix</a></li>
<li class="chapter" data-level="17.4" data-path="jacobian-17.html"><a href="jacobian-17.html#exercises-16"><i class="fa fa-check"></i><b>17.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html"><i class="fa fa-check"></i><b>18</b> What are Eigenvalues?</a>
<ul>
<li class="chapter" data-level="18.1" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#introduction"><i class="fa fa-check"></i><b>18.1</b> Introduction</a></li>
<li class="chapter" data-level="18.2" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#straight-line-solutions"><i class="fa fa-check"></i><b>18.2</b> Straight line solutions</a></li>
<li class="chapter" data-level="18.3" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#computing-eigenvalues-and-eigenvectors"><i class="fa fa-check"></i><b>18.3</b> Computing eigenvalues and eigenvectors</a></li>
<li class="chapter" data-level="18.4" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#what-do-eigenvalues-tell-us"><i class="fa fa-check"></i><b>18.4</b> What do eigenvalues tell us?</a></li>
<li class="chapter" data-level="18.5" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#concluding-thoughts-1"><i class="fa fa-check"></i><b>18.5</b> Concluding thoughts</a></li>
<li class="chapter" data-level="18.6" data-path="eigenvalues-18.html"><a href="eigenvalues-18.html#exercises-17"><i class="fa fa-check"></i><b>18.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="stability-19.html"><a href="stability-19.html"><i class="fa fa-check"></i><b>19</b> Qualitative Stability Analysis</a>
<ul>
<li class="chapter" data-level="19.1" data-path="stability-19.html"><a href="stability-19.html#the-characteristic-polynomial-again"><i class="fa fa-check"></i><b>19.1</b> The characteristic polynomial (again)</a></li>
<li class="chapter" data-level="19.2" data-path="stability-19.html"><a href="stability-19.html#stability-with-the-trace-and-determinant"><i class="fa fa-check"></i><b>19.2</b> Stability with the trace and determinant</a></li>
<li class="chapter" data-level="19.3" data-path="stability-19.html"><a href="stability-19.html#a-workflow-for-stability-analysis"><i class="fa fa-check"></i><b>19.3</b> A workflow for stability analysis</a></li>
<li class="chapter" data-level="19.4" data-path="stability-19.html"><a href="stability-19.html#stability-for-higher-order-systems-of-differential-equations."><i class="fa fa-check"></i><b>19.4</b> Stability for higher-order systems of differential equations.</a></li>
<li class="chapter" data-level="19.5" data-path="stability-19.html"><a href="stability-19.html#exercises-18"><i class="fa fa-check"></i><b>19.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="bifurcation-20.html"><a href="bifurcation-20.html"><i class="fa fa-check"></i><b>20</b> Bifurcation</a>
<ul>
<li class="chapter" data-level="20.1" data-path="bifurcation-20.html"><a href="bifurcation-20.html#a-series-of-equations"><i class="fa fa-check"></i><b>20.1</b> A series of equations</a></li>
<li class="chapter" data-level="20.2" data-path="bifurcation-20.html"><a href="bifurcation-20.html#bifurcations-with-systems-of-equations"><i class="fa fa-check"></i><b>20.2</b> Bifurcations with systems of equations</a></li>
<li class="chapter" data-level="20.3" data-path="bifurcation-20.html"><a href="bifurcation-20.html#functions-as-equilibrium-solutions-limit-cycles"><i class="fa fa-check"></i><b>20.3</b> Functions as equilibrium solutions: limit cycles</a></li>
<li class="chapter" data-level="20.4" data-path="bifurcation-20.html"><a href="bifurcation-20.html#bifurcations-as-analysis-tools"><i class="fa fa-check"></i><b>20.4</b> Bifurcations as analysis tools</a></li>
<li class="chapter" data-level="20.5" data-path="bifurcation-20.html"><a href="bifurcation-20.html#exercises-19"><i class="fa fa-check"></i><b>20.5</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>IV Stochastic Differential Equations</b></span></li>
<li class="chapter" data-level="21" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html"><i class="fa fa-check"></i><b>21</b> Stochastic Biological Systems</a>
<ul>
<li class="chapter" data-level="21.1" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html#introducing-stochastic-effects"><i class="fa fa-check"></i><b>21.1</b> Introducing stochastic effects</a></li>
<li class="chapter" data-level="21.2" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html#a-discrete-dynamical-system"><i class="fa fa-check"></i><b>21.2</b> A discrete dynamical system</a></li>
<li class="chapter" data-level="21.3" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html#environmental-stochasticity"><i class="fa fa-check"></i><b>21.3</b> Environmental stochasticity</a></li>
<li class="chapter" data-level="21.4" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html#discrete-systems-of-equations"><i class="fa fa-check"></i><b>21.4</b> Discrete systems of equations</a></li>
<li class="chapter" data-level="21.5" data-path="stoch-sys-21.html"><a href="stoch-sys-21.html#exercises-20"><i class="fa fa-check"></i><b>21.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="stoch-sim-22.html"><a href="stoch-sim-22.html"><i class="fa fa-check"></i><b>22</b> Simulating and Visualizing Randomness</a>
<ul>
<li class="chapter" data-level="22.1" data-path="stoch-sim-22.html"><a href="stoch-sim-22.html#ensemble-averages"><i class="fa fa-check"></i><b>22.1</b> Ensemble averages</a></li>
<li class="chapter" data-level="22.2" data-path="stoch-sim-22.html"><a href="stoch-sim-22.html#repeated-iteration"><i class="fa fa-check"></i><b>22.2</b> Repeated iteration</a></li>
<li class="chapter" data-level="22.3" data-path="stoch-sim-22.html"><a href="stoch-sim-22.html#exercises-21"><i class="fa fa-check"></i><b>22.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="random-walks-23.html"><a href="random-walks-23.html"><i class="fa fa-check"></i><b>23</b> Random Walks</a>
<ul>
<li class="chapter" data-level="23.1" data-path="random-walks-23.html"><a href="random-walks-23.html#random-walk-on-a-number-line"><i class="fa fa-check"></i><b>23.1</b> Random walk on a number line</a></li>
<li class="chapter" data-level="23.2" data-path="random-walks-23.html"><a href="random-walks-23.html#iteration-and-ensemble-averages"><i class="fa fa-check"></i><b>23.2</b> Iteration and ensemble averages</a></li>
<li class="chapter" data-level="23.3" data-path="random-walks-23.html"><a href="random-walks-23.html#random-walk-mathematics"><i class="fa fa-check"></i><b>23.3</b> Random walk mathematics</a></li>
<li class="chapter" data-level="23.4" data-path="random-walks-23.html"><a href="random-walks-23.html#continuous-random-walks-and-diffusion"><i class="fa fa-check"></i><b>23.4</b> Continuous random walks and diffusion</a></li>
<li class="chapter" data-level="23.5" data-path="random-walks-23.html"><a href="random-walks-23.html#exercises-22"><i class="fa fa-check"></i><b>23.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="diffusion-24.html"><a href="diffusion-24.html"><i class="fa fa-check"></i><b>24</b> Diffusion and Brownian Motion</a>
<ul>
<li class="chapter" data-level="24.1" data-path="diffusion-24.html"><a href="diffusion-24.html#random-walk-redux"><i class="fa fa-check"></i><b>24.1</b> Random walk redux</a></li>
<li class="chapter" data-level="24.2" data-path="diffusion-24.html"><a href="diffusion-24.html#simulating-brownian-motion"><i class="fa fa-check"></i><b>24.2</b> Simulating Brownian motion</a></li>
<li class="chapter" data-level="24.3" data-path="diffusion-24.html"><a href="diffusion-24.html#exercises-23"><i class="fa fa-check"></i><b>24.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="sdes-25.html"><a href="sdes-25.html"><i class="fa fa-check"></i><b>25</b> Simulating Stochastic Differential Equations</a>
<ul>
<li class="chapter" data-level="25.1" data-path="sdes-25.html"><a href="sdes-25.html#the-stochastic-logistic-model"><i class="fa fa-check"></i><b>25.1</b> The stochastic logistic model</a></li>
<li class="chapter" data-level="25.2" data-path="sdes-25.html"><a href="sdes-25.html#the-euler-maruyama-method"><i class="fa fa-check"></i><b>25.2</b> The Euler-Maruyama method</a></li>
<li class="chapter" data-level="25.3" data-path="sdes-25.html"><a href="sdes-25.html#adding-stochasticity-to-parameters"><i class="fa fa-check"></i><b>25.3</b> Adding stochasticity to parameters</a></li>
<li class="chapter" data-level="25.4" data-path="sdes-25.html"><a href="sdes-25.html#systems-of-stochastic-differential-equations"><i class="fa fa-check"></i><b>25.4</b> Systems of stochastic differential equations</a></li>
<li class="chapter" data-level="25.5" data-path="sdes-25.html"><a href="sdes-25.html#concluding-thoughts-2"><i class="fa fa-check"></i><b>25.5</b> Concluding thoughts</a></li>
<li class="chapter" data-level="25.6" data-path="sdes-25.html"><a href="sdes-25.html#exercises-24"><i class="fa fa-check"></i><b>25.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="simul-stoch-26.html"><a href="simul-stoch-26.html"><i class="fa fa-check"></i><b>26</b> Statistics of a Stochastic Differential Equation</a>
<ul>
<li class="chapter" data-level="26.1" data-path="simul-stoch-26.html"><a href="simul-stoch-26.html#expected-value-of-a-stochastic-process"><i class="fa fa-check"></i><b>26.1</b> Expected value of a stochastic process</a></li>
<li class="chapter" data-level="26.2" data-path="simul-stoch-26.html"><a href="simul-stoch-26.html#birth-death-processes"><i class="fa fa-check"></i><b>26.2</b> Birth-death processes</a></li>
<li class="chapter" data-level="26.3" data-path="simul-stoch-26.html"><a href="simul-stoch-26.html#wrapping-up"><i class="fa fa-check"></i><b>26.3</b> Wrapping up</a></li>
<li class="chapter" data-level="26.4" data-path="simul-stoch-26.html"><a href="simul-stoch-26.html#exercises-25"><i class="fa fa-check"></i><b>26.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="solvingSDEs-27.html"><a href="solvingSDEs-27.html"><i class="fa fa-check"></i><b>27</b> Solutions to Stochastic Differential Equations</a>
<ul>
<li class="chapter" data-level="27.1" data-path="solvingSDEs-27.html"><a href="solvingSDEs-27.html#meet-the-fokker-planck-equation"><i class="fa fa-check"></i><b>27.1</b> Meet the Fokker-Planck equation</a></li>
<li class="chapter" data-level="27.2" data-path="solvingSDEs-27.html"><a href="solvingSDEs-27.html#deterministically-the-end"><i class="fa fa-check"></i><b>27.2</b> Deterministically the end</a></li>
<li class="chapter" data-level="27.3" data-path="solvingSDEs-27.html"><a href="solvingSDEs-27.html#exercises-26"><i class="fa fa-check"></i><b>27.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a></li>
<li><a href="https://bookdown.org" target="_blank">Built with Bookdown + RStudio</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Exploring Modeling with Data and Differential Equations Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="stoch-sim-22" class="section level1 hasAnchor" number="22">
<h1><span class="header-section-number">Chapter 22</span> Simulating and Visualizing Randomness<a href="stoch-sim-22.html#stoch-sim-22" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In Chapter <a href="stoch-sys-21.html#stoch-sys-21">21</a> we examined models for stochastic biological systems. These types of models are an introduction to the study of stochastic differential equations (SDEs). A common theme to SDEs is learning how to analyze and visualize randomness, broadly defined. In order to do that we will need to level up our skills to summarize a cohort of simulations over time. Let’s get started!</p>
<div id="ensemble-averages" class="section level2 hasAnchor" number="22.1">
<h2><span class="header-section-number">22.1</span> Ensemble averages<a href="stoch-sim-22.html#ensemble-averages" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Consider Figure <a href="stoch-sim-22.html#fig:kuopio-weather">22.1</a>, which shows the weather forecast for Kuopio, a city in Finland <span class="citation">(<a href="#ref-finnish_meteorological_institute_weather_2021">Finnish Meteorological Institute 2021</a>)</span>:<a href="#fn45" class="footnote-ref" id="fnref45"><sup>45</sup></a></p>
<div class="figure"><span style="display:block;" id="fig:kuopio-weather"></span>
<img src="figures/22-simulation/kuopio.png" alt="Long term weather forecast for Kuopio, a city in Finland, from the Finnish Weather Institute. Accessed 16-Dec 2021." width="80%" />
<p class="caption">
FIGURE 22.1: Long term weather forecast for Kuopio, a city in Finland, from the Finnish Weather Institute. Accessed 16-Dec 2021.
</p>
</div>
<p>Figure <a href="stoch-sim-22.html#fig:kuopio-weather">22.1</a> shows a great example of what is called an <em>ensemble average</em>. The horizontal axis lists the time of day and the vertical axis is the temperature (the bar graph represents precipitation). The forecast temperature at a given point in time can have a range of outcomes, with the median of the distribution as the “temperature probability forecast”<a href="#fn46" class="footnote-ref" id="fnref46"><sup>46</sup></a>. The red shading states that 80% of the outcomes fall in a given range, so while the median temperature on Monday, December 20 (labeled as Mo 20.12 - dates are represented as DAY-MONTH-YEAR) is <span class="math inline">\(-10^{\circ}\)</span>C, it may range between <span class="math inline">\(-16\)</span> and <span class="math inline">\(-4^{\circ}\)</span>C (3 to 24 <span class="math inline">\(^{\circ}\)</span>F, brrr!). Based on the legends given, we would say the 80% confidence interval is between <span class="math inline">\(-10\)</span> to <span class="math inline">\(-4^{\circ}\)</span>C, or the models have 80% confidence for the temperature to be between that range of temperatures.</p>
<p>Because there may be different factors that alter the weather in a particular spot (e.g. the timing of a low pressure front, clouds, etc.) there are different possibilities for an outcome of the weather forecast. While it may seem like forecasting weather is impossible to do, sometimes these changes lead to small fluctuations in the forecasted weather at a given point. The ensemble average in Figure <a href="stoch-sim-22.html#fig:kuopio-weather">22.1</a> becomes more uncertain (wider shading), as unforeseen events may drastically change the weather in the long term.</p>
<div id="spaghetti-plots" class="section level3 hasAnchor" number="22.1.1">
<h3><span class="header-section-number">22.1.1</span> Spaghetti plots<a href="stoch-sim-22.html#spaghetti-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now let’s focus on how to construct an ensemble average, but first let’s start with a sample dataset. Consider the following data in Table <a href="stoch-sim-22.html#tab:simul-table">22.1</a>. Notice how all the simulations (<code>sim1</code>, <code>sim2</code>, <code>sim3</code>) share the variable <code>t</code> in common, so it makes sense to plot them on the same axis in Figure <a href="stoch-sim-22.html#fig:simul-graph-prev">22.2</a>. We call a plot of all of the simulations together a <em>spaghetti plot</em>, because, well, it can look like a bowl of spaghetti noodles was dumped all over the plotting space.</p>
<table>
<caption>
<span id="tab:simul-table">TABLE 22.1: </span>Simulations of a variable at different times.
</caption>
<thead>
<tr>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
sim1
</th>
<th style="text-align:right;">
sim2
</th>
<th style="text-align:right;">
sim3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3.39
</td>
<td style="text-align:right;">
2.16
</td>
<td style="text-align:right;">
1.93
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:right;">
3.99
</td>
<td style="text-align:right;">
4.53
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2.92
</td>
<td style="text-align:right;">
4.85
</td>
<td style="text-align:right;">
3.15
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
4.05
</td>
<td style="text-align:right;">
3.68
</td>
<td style="text-align:right;">
4.65
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
1.65
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
3.82
</td>
</tr>
</tbody>
</table>
<div class="figure"><span style="display:block;" id="fig:simul-graph-prev"></span>
<img src="explore-model-zobitz-220419_files/figure-html/simul-graph-prev-1.png" alt="Spaghetti plot of the three simulations from Table \@ref(tab:simul-table)." width="672" />
<p class="caption">
FIGURE 22.2: Spaghetti plot of the three simulations from Table <a href="stoch-sim-22.html#tab:simul-table">22.1</a>.
</p>
</div>
<p>While making the spaghetti plot isn’t bad when you have three simulations, with (a lot) more simulations this would be a pain! An ensemble average computes <em>across</em> the rows in Table <a href="stoch-sim-22.html#tab:simul-table">22.1</a> (could be an average or a quantile) to generate a new column in the data. Building an ensemble average is a step by step process that involves a series of processes that transform a dataset where you will need to first pivot the dataset and then group and summarize.</p>
</div>
<div id="pivot" class="section level3 hasAnchor" number="22.1.2">
<h3><span class="header-section-number">22.1.2</span> Pivot<a href="stoch-sim-22.html#pivot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When you have multiple columns of a plot that you want to show together (such as a spaghetti plot) we can use a command called <code>pivot_longer</code> that gathers different columns together (also shown in Table <a href="stoch-sim-22.html#tab:simul-table-long">22.2</a>).</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="stoch-sim-22.html#cb84-1" tabindex="-1"></a>my_table_long <span class="ot">&lt;-</span> my_table <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="stoch-sim-22.html#cb84-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(<span class="st">&quot;sim1&quot;</span><span class="sc">:</span><span class="st">&quot;sim3&quot;</span>), </span>
<span id="cb84-3"><a href="stoch-sim-22.html#cb84-3" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;name&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;value&quot;</span>)</span></code></pre></div>
<table>
<caption>
<span id="tab:simul-table-long">TABLE 22.2: </span>Simulations of a variable at different times, condensed into a long table.
</caption>
<thead>
<tr>
<th style="text-align:right;">
t
</th>
<th style="text-align:left;">
name
</th>
<th style="text-align:right;">
value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
sim1
</td>
<td style="text-align:right;">
3.39
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
sim2
</td>
<td style="text-align:right;">
2.16
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
sim3
</td>
<td style="text-align:right;">
1.93
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
sim1
</td>
<td style="text-align:right;">
0.16
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
sim2
</td>
<td style="text-align:right;">
3.99
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
sim3
</td>
<td style="text-align:right;">
4.53
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
sim1
</td>
<td style="text-align:right;">
2.92
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
sim2
</td>
<td style="text-align:right;">
4.85
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
sim3
</td>
<td style="text-align:right;">
3.15
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
sim1
</td>
<td style="text-align:right;">
4.05
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
sim2
</td>
<td style="text-align:right;">
3.68
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
sim3
</td>
<td style="text-align:right;">
4.65
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
sim1
</td>
<td style="text-align:right;">
1.65
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
sim2
</td>
<td style="text-align:right;">
0.23
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
sim3
</td>
<td style="text-align:right;">
3.82
</td>
</tr>
</tbody>
</table>
<p>Notice how the command <code>pivot_longer</code> takes the different simulations (<code>sim1</code>, <code>sim2</code>, <code>sim3</code>) and reassigns the column names to a new column called <code>name</code>, with values in the different columns appropriately assigned to the column <code>value</code>. This process called pivoting creates a new data frame, which makes it easier to generate the spaghetti plot (Figure <a href="stoch-sim-22.html#fig:simul-graph-prev">22.2</a>). Try the following code out on your own to confirm this:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="stoch-sim-22.html#cb85-1" tabindex="-1"></a>my_table_long <span class="sc">%&gt;%</span></span>
<span id="cb85-2"><a href="stoch-sim-22.html#cb85-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> value, <span class="at">group =</span> name)) <span class="sc">+</span></span>
<span id="cb85-3"><a href="stoch-sim-22.html#cb85-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb85-4"><a href="stoch-sim-22.html#cb85-4" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb85-5"><a href="stoch-sim-22.html#cb85-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Simulation Value&quot;</span>)</span></code></pre></div>
</div>
<div id="group-and-summarize" class="section level3 hasAnchor" number="22.1.3">
<h3><span class="header-section-number">22.1.3</span> Group and summarize<a href="stoch-sim-22.html#group-and-summarize" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The next step after pivoting is to collect the time points at <span class="math inline">\(t=1\)</span> together, <span class="math inline">\(t=2\)</span> together, and so on. In each of these groups we then compute the mean (average). This process is called <em>grouping</em> and then applying a <em>summarizing</em> function to all the members in a particular group (which in this case is the <code>mean</code>). The code to do this summarizing is shown below, with the results in Table <a href="stoch-sim-22.html#tab:table-summary">22.3</a>:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="stoch-sim-22.html#cb86-1" tabindex="-1"></a>summarized_table <span class="ot">&lt;-</span> my_table_long <span class="sc">%&gt;%</span></span>
<span id="cb86-2"><a href="stoch-sim-22.html#cb86-2" tabindex="-1"></a>  <span class="fu">group_by</span>(t) <span class="sc">%&gt;%</span></span>
<span id="cb86-3"><a href="stoch-sim-22.html#cb86-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_val =</span> <span class="fu">mean</span>(value))</span></code></pre></div>
<table>
<caption>
<span id="tab:table-summary">TABLE 22.3: </span>Ensemble averages for the three simulations at each of the times <span class="math inline">\(t\)</span>.
</caption>
<tbody>
<tr>
<td style="text-align:left;">
t
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
2.00
</td>
<td style="text-align:right;">
3.00
</td>
<td style="text-align:right;">
4.00
</td>
<td style="text-align:right;">
5.0
</td>
</tr>
<tr>
<td style="text-align:left;">
mean_val
</td>
<td style="text-align:right;">
2.49
</td>
<td style="text-align:right;">
2.89
</td>
<td style="text-align:right;">
3.64
</td>
<td style="text-align:right;">
4.13
</td>
<td style="text-align:right;">
1.9
</td>
</tr>
</tbody>
</table>
<p>Notice how we are using the pipe <code>%&gt;%</code> command to help organize the actions that we are doing. Think of the pipe as part of a multistep process - similar to function composition. Here is how you can read the previous code:</p>
<p>To compute the variable <code>summarized_table</code> we will:</p>
<ul>
<li><strong>First</strong> start with the data frame <code>my_table_long</code>,</li>
<li><strong>Second</strong> signal to <code>R</code> to <code>group_by</code> the variable <code>t</code> (collect similar values together) in order to,</li>
<li><strong>Third</strong> compute the mean.</li>
</ul>
<p>To explain this code a little more:</p>
<ul>
<li>The command <code>group_by(t)</code> means collect similar time points together.</li>
<li>The next line computes the mean. The command <code>summarize</code> means that we are going to create a new data frame column (labeled <code>mean_val</code> that is the mean of all the grouped times, from the <code>value</code> column.</li>
</ul>
<p>We can add this mean value to our data (Figure <a href="stoch-sim-22.html#fig:simul-graph-prev">22.2</a>), represented with a thick red line. Try the following code out on your own:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="stoch-sim-22.html#cb87-1" tabindex="-1"></a>my_table_long <span class="sc">%&gt;%</span></span>
<span id="cb87-2"><a href="stoch-sim-22.html#cb87-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> value, <span class="at">group =</span> name)) <span class="sc">+</span></span>
<span id="cb87-3"><a href="stoch-sim-22.html#cb87-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb87-4"><a href="stoch-sim-22.html#cb87-4" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb87-5"><a href="stoch-sim-22.html#cb87-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> summarized_table, </span>
<span id="cb87-6"><a href="stoch-sim-22.html#cb87-6" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> mean_val), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>, </span>
<span id="cb87-7"><a href="stoch-sim-22.html#cb87-7" tabindex="-1"></a>            <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb87-8"><a href="stoch-sim-22.html#cb87-8" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> summarized_table, <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> mean_val), </span>
<span id="cb87-9"><a href="stoch-sim-22.html#cb87-9" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>, </span>
<span id="cb87-10"><a href="stoch-sim-22.html#cb87-10" tabindex="-1"></a>             <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb87-11"><a href="stoch-sim-22.html#cb87-11" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-12"><a href="stoch-sim-22.html#cb87-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Simulation Value&quot;</span>)</span></code></pre></div>
<p>Notice two things:</p>
<ul>
<li>We can use the pipe (<code>%&gt;%</code>) to the workflow before plotting with <code>ggplot</code>. This signals that <code>my_table_long</code> is the input data into <code>ggplot</code>.</li>
<li>We included the option <code>inherit.aes = FALSE</code> (<code>inherit.aes</code> stands for “inherit aesthetics” ) when we plotted <code>summarized_table</code> with <code>geom_point</code> and <code>geom_line</code>. When you add a new data frame to a plot, the initial aesthetics (such as the <code>color</code> or the <code>group</code>) are passed on to subsequent commands. Setting <code>inherit.aes = FALSE</code> allows you to work with a clean slate.</li>
</ul>
</div>
</div>
<div id="repeated-iteration" class="section level2 hasAnchor" number="22.2">
<h2><span class="header-section-number">22.2</span> Repeated iteration<a href="stoch-sim-22.html#repeated-iteration" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The previous example introduced the concept of pivoting data and computing an ensemble mean. Let’s put this into additional practice with examples we have studied previously. Let’s work with the logistic differential equation <span class="math inline">\(\displaystyle \frac{dx}{dt} = rx\left(1- \frac{x}{K}\right)\)</span>. Our goal is to examine how different (random) initial conditions affect the modeled solution trajectories. The way we will approach this problem is with the following workflow:</p>
<blockquote>
<p>Do once <span class="math inline">\(\rightarrow\)</span> Do several times <span class="math inline">\(\rightarrow\)</span> Summarize <span class="math inline">\(\rightarrow\)</span> Visualize</p>
</blockquote>
<p>We will apply this workflow step by step with code and results provided.</p>
<div id="do-once" class="section level3 hasAnchor" number="22.2.1">
<h3><span class="header-section-number">22.2.1</span> Do once<a href="stoch-sim-22.html#do-once" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To investigate the effect of the initial condition on the solution we will choose the initial condition from a uniform distribution between 0 and 20, shown in the following code and plotted in Figure <a href="stoch-sim-22.html#fig:logistic-example-rev">22.3</a>:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="stoch-sim-22.html#cb88-1" tabindex="-1"></a><span class="co"># Define the rate equation</span></span>
<span id="cb88-2"><a href="stoch-sim-22.html#cb88-2" tabindex="-1"></a>logistic_eq <span class="ot">&lt;-</span> <span class="fu">c</span>(dx <span class="sc">~</span> r <span class="sc">*</span> x <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> x <span class="sc">/</span> K)) </span>
<span id="cb88-3"><a href="stoch-sim-22.html#cb88-3" tabindex="-1"></a></span>
<span id="cb88-4"><a href="stoch-sim-22.html#cb88-4" tabindex="-1"></a><span class="co"># Identify any parameters</span></span>
<span id="cb88-5"><a href="stoch-sim-22.html#cb88-5" tabindex="-1"></a>params <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">r =</span> .<span class="dv">8</span>, <span class="at">K =</span> <span class="dv">100</span>) </span>
<span id="cb88-6"><a href="stoch-sim-22.html#cb88-6" tabindex="-1"></a></span>
<span id="cb88-7"><a href="stoch-sim-22.html#cb88-7" tabindex="-1"></a><span class="co"># Random initial condition number 1</span></span>
<span id="cb88-8"><a href="stoch-sim-22.html#cb88-8" tabindex="-1"></a>init_cond_rand <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">20</span>)) </span>
<span id="cb88-9"><a href="stoch-sim-22.html#cb88-9" tabindex="-1"></a></span>
<span id="cb88-10"><a href="stoch-sim-22.html#cb88-10" tabindex="-1"></a>soln_rand <span class="ot">&lt;-</span> <span class="fu">euler</span>(</span>
<span id="cb88-11"><a href="stoch-sim-22.html#cb88-11" tabindex="-1"></a>  <span class="at">system_eq =</span> logistic_eq,</span>
<span id="cb88-12"><a href="stoch-sim-22.html#cb88-12" tabindex="-1"></a>  <span class="at">initial_condition =</span> init_cond_rand,</span>
<span id="cb88-13"><a href="stoch-sim-22.html#cb88-13" tabindex="-1"></a>  <span class="at">parameters =</span> params,</span>
<span id="cb88-14"><a href="stoch-sim-22.html#cb88-14" tabindex="-1"></a>  <span class="at">deltaT =</span> .<span class="dv">05</span>,</span>
<span id="cb88-15"><a href="stoch-sim-22.html#cb88-15" tabindex="-1"></a>  <span class="at">n_steps =</span> <span class="dv">200</span></span>
<span id="cb88-16"><a href="stoch-sim-22.html#cb88-16" tabindex="-1"></a>)</span>
<span id="cb88-17"><a href="stoch-sim-22.html#cb88-17" tabindex="-1"></a></span>
<span id="cb88-18"><a href="stoch-sim-22.html#cb88-18" tabindex="-1"></a><span class="co"># Random initial condition number 2</span></span>
<span id="cb88-19"><a href="stoch-sim-22.html#cb88-19" tabindex="-1"></a>init_cond_rand_two <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">20</span>)) </span>
<span id="cb88-20"><a href="stoch-sim-22.html#cb88-20" tabindex="-1"></a></span>
<span id="cb88-21"><a href="stoch-sim-22.html#cb88-21" tabindex="-1"></a>soln_rand_two <span class="ot">&lt;-</span> <span class="fu">euler</span>(</span>
<span id="cb88-22"><a href="stoch-sim-22.html#cb88-22" tabindex="-1"></a>  <span class="at">system_eq =</span> logistic_eq,</span>
<span id="cb88-23"><a href="stoch-sim-22.html#cb88-23" tabindex="-1"></a>  <span class="at">initial_condition =</span> init_cond_rand_two,</span>
<span id="cb88-24"><a href="stoch-sim-22.html#cb88-24" tabindex="-1"></a>  <span class="at">parameters =</span> params,</span>
<span id="cb88-25"><a href="stoch-sim-22.html#cb88-25" tabindex="-1"></a>  <span class="at">deltaT =</span> .<span class="dv">05</span>,</span>
<span id="cb88-26"><a href="stoch-sim-22.html#cb88-26" tabindex="-1"></a>  <span class="at">n_steps =</span> <span class="dv">200</span></span>
<span id="cb88-27"><a href="stoch-sim-22.html#cb88-27" tabindex="-1"></a>)</span>
<span id="cb88-28"><a href="stoch-sim-22.html#cb88-28" tabindex="-1"></a></span>
<span id="cb88-29"><a href="stoch-sim-22.html#cb88-29" tabindex="-1"></a><span class="co"># Plot your solutions:</span></span>
<span id="cb88-30"><a href="stoch-sim-22.html#cb88-30" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb88-31"><a href="stoch-sim-22.html#cb88-31" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> soln_rand, <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> x), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-32"><a href="stoch-sim-22.html#cb88-32" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> soln_rand_two, <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> x), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-33"><a href="stoch-sim-22.html#cb88-33" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb88-34"><a href="stoch-sim-22.html#cb88-34" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Time&quot;</span>,</span>
<span id="cb88-35"><a href="stoch-sim-22.html#cb88-35" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;x&quot;</span></span>
<span id="cb88-36"><a href="stoch-sim-22.html#cb88-36" tabindex="-1"></a>  ) </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:logistic-example-rev"></span>
<img src="explore-model-zobitz-220419_files/figure-html/logistic-example-rev-1.png" alt="Two solutions to the logistic differential equation with a random initial condition." width="672" />
<p class="caption">
FIGURE 22.3: Two solutions to the logistic differential equation with a random initial condition.
</p>
</div>
</div>
<div id="do-several-times" class="section level3 hasAnchor" number="22.2.2">
<h3><span class="header-section-number">22.2.2</span> Do several times<a href="stoch-sim-22.html#do-several-times" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Running several hundred iterations of this model could quickly grow time consuming. Fortunately we can use iteration here to compute and gather several different solutions. First the code, followed by a deconstruction:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="stoch-sim-22.html#cb89-1" tabindex="-1"></a>n_sims <span class="ot">&lt;-</span> <span class="dv">500</span> <span class="co"># The number of simulations</span></span>
<span id="cb89-2"><a href="stoch-sim-22.html#cb89-2" tabindex="-1"></a></span>
<span id="cb89-3"><a href="stoch-sim-22.html#cb89-3" tabindex="-1"></a><span class="co"># Compute solutions</span></span>
<span id="cb89-4"><a href="stoch-sim-22.html#cb89-4" tabindex="-1"></a>logistic_sim <span class="ot">&lt;-</span> <span class="fu">rerun</span>(n_sims, <span class="fu">c</span>(<span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">20</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb89-5"><a href="stoch-sim-22.html#cb89-5" tabindex="-1"></a>  <span class="fu">set_names</span>(<span class="fu">paste0</span>(<span class="st">&quot;sim&quot;</span>, <span class="dv">1</span><span class="sc">:</span>n_sims)) <span class="sc">%&gt;%</span></span>
<span id="cb89-6"><a href="stoch-sim-22.html#cb89-6" tabindex="-1"></a>  <span class="fu">map</span>(<span class="sc">~</span> <span class="fu">euler</span>(</span>
<span id="cb89-7"><a href="stoch-sim-22.html#cb89-7" tabindex="-1"></a>    <span class="at">system_eq =</span> logistic_eq,</span>
<span id="cb89-8"><a href="stoch-sim-22.html#cb89-8" tabindex="-1"></a>    <span class="at">initial_condition =</span> .x,</span>
<span id="cb89-9"><a href="stoch-sim-22.html#cb89-9" tabindex="-1"></a>    <span class="at">parameters =</span> params,</span>
<span id="cb89-10"><a href="stoch-sim-22.html#cb89-10" tabindex="-1"></a>    <span class="at">deltaT =</span> .<span class="dv">05</span>,</span>
<span id="cb89-11"><a href="stoch-sim-22.html#cb89-11" tabindex="-1"></a>    <span class="at">n_steps =</span> <span class="dv">200</span></span>
<span id="cb89-12"><a href="stoch-sim-22.html#cb89-12" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb89-13"><a href="stoch-sim-22.html#cb89-13" tabindex="-1"></a>  <span class="fu">map_dfr</span>(<span class="sc">~</span>.x, <span class="at">.id =</span> <span class="st">&quot;simulation&quot;</span>)</span>
<span id="cb89-14"><a href="stoch-sim-22.html#cb89-14" tabindex="-1"></a></span>
<span id="cb89-15"><a href="stoch-sim-22.html#cb89-15" tabindex="-1"></a><span class="co"># Plot these all together</span></span>
<span id="cb89-16"><a href="stoch-sim-22.html#cb89-16" tabindex="-1"></a>logistic_sim <span class="sc">%&gt;%</span></span>
<span id="cb89-17"><a href="stoch-sim-22.html#cb89-17" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> x)) <span class="sc">+</span></span>
<span id="cb89-18"><a href="stoch-sim-22.html#cb89-18" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color =</span> simulation)) <span class="sc">+</span></span>
<span id="cb89-19"><a href="stoch-sim-22.html#cb89-19" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Random initial conditions&quot;</span>) <span class="sc">+</span></span>
<span id="cb89-20"><a href="stoch-sim-22.html#cb89-20" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: `rerun()` was deprecated in purrr 1.0.0.
## ℹ Please use `map()` instead.
##   # Previously
##   rerun(500, c(x = runif(1, min = 0, max = 20)))
## 
##   # Now
##   map(1:500, ~ c(x = runif(1, min = 0, max = 20)))
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this
## warning was generated.</code></pre>
<div class="figure"><span style="display:block;" id="fig:logistic-example-many"></span>
<img src="explore-model-zobitz-220419_files/figure-html/logistic-example-many-1.png" alt="Spaghetti plot for logistic differential equation with 500 random initial conditions." width="672" />
<p class="caption">
FIGURE 22.4: Spaghetti plot for logistic differential equation with 500 random initial conditions.
</p>
</div>
<p>Wow! This spaghetti plot is really interesting - it should show how even though the initial conditions vary between <span class="math inline">\(x=0\)</span> to <span class="math inline">\(x=20\)</span>, eventually all solutions flow to the carrying capacity <span class="math inline">\(K=100\)</span> (which is a stable equilbrium solution). Initial conditions that start closer to <span class="math inline">\(x=0\)</span> take longer, mainly because they are so close to the other equilibrium solution at <span class="math inline">\(x=0\)</span> (which is an unstable equilibrium solution).</p>
<p>Ok, let’s deconstruct this code line by line:</p>
<ul>
<li><code>rerun(n_sims, c(x=runif(1,min=0,max=20)))</code> This line does two things: <code>x=runif(1,min=0,max=20)</code> makes a random initial condition, and the command <code>rerun</code> runs this again for <code>n_sims</code> times.</li>
<li><code>set_names(paste0("sim", 1:n_sims))</code> This line distinguishes between all the different simulations.</li>
<li><code>map(~ euler( ... )</code> You should be familiar with <code>euler</code>, but notice the pronoun <code>.x</code> that substitutes all the different initial conditions into Euler’s method. The <code>map</code> function iterates over each of the simulations.</li>
<li><code>map_dfr(~ .x, .id = "simulation")</code> This line binds everything up together.</li>
</ul>
<p>The resulting data frame should have three columns:
- <code>simulation</code>: which one of the 500 simulations (<code>sim1</code>, <code>sim2</code>, etc …) this corresponds to.
- <code>t</code>: the value of the time
- <code>x</code>: the output value of the variable x.</p>
<p>This code applies a new concept called <em>functional programming</em>. This is a powerful tool that allows you to perform the process of iteration (do the same thing repeatedly) with uncluttered code. We won’t delve more into this here, but I encourage you to read about more functional programming concepts in <span class="citation">Wickham and Grolemund (<a href="#ref-wickham_r_2017">2017</a>)</span>.</p>
</div>
<div id="summarize" class="section level3 hasAnchor" number="22.2.3">
<h3><span class="header-section-number">22.2.3</span> Summarize<a href="stoch-sim-22.html#summarize" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Computing the ensemble average requires knowledge of how to use <code>R</code> to compute percentiles from a distribution of values. For our purposes here we will use the 95% confidence interval, so that means the 2.5 and 97.5 percentile (in which only 5% of the values will be outside of the specified interval), along with the median value (50th percentile). Let’s take a look at the code for how to do that:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="stoch-sim-22.html#cb91-1" tabindex="-1"></a>quantile_vals <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>)</span>
<span id="cb91-2"><a href="stoch-sim-22.html#cb91-2" tabindex="-1"></a></span>
<span id="cb91-3"><a href="stoch-sim-22.html#cb91-3" tabindex="-1"></a>logistic_quantile <span class="ot">&lt;-</span> logistic_sim <span class="sc">%&gt;%</span></span>
<span id="cb91-4"><a href="stoch-sim-22.html#cb91-4" tabindex="-1"></a>  <span class="fu">group_by</span>(t) <span class="sc">%&gt;%</span></span>
<span id="cb91-5"><a href="stoch-sim-22.html#cb91-5" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb91-6"><a href="stoch-sim-22.html#cb91-6" tabindex="-1"></a>    <span class="at">q_val =</span> <span class="fu">quantile</span>(x,   <span class="co"># x is the column to compute the quantiles</span></span>
<span id="cb91-7"><a href="stoch-sim-22.html#cb91-7" tabindex="-1"></a>      <span class="at">probs =</span> quantile_vals</span>
<span id="cb91-8"><a href="stoch-sim-22.html#cb91-8" tabindex="-1"></a>    ),</span>
<span id="cb91-9"><a href="stoch-sim-22.html#cb91-9" tabindex="-1"></a>    <span class="at">q_name =</span> quantile_vals</span>
<span id="cb91-10"><a href="stoch-sim-22.html#cb91-10" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb91-11"><a href="stoch-sim-22.html#cb91-11" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">&quot;q_name&quot;</span>, <span class="at">values_from =</span> <span class="st">&quot;q_val&quot;</span>, </span>
<span id="cb91-12"><a href="stoch-sim-22.html#cb91-12" tabindex="-1"></a>              <span class="at">names_glue =</span> <span class="st">&quot;q{q_name}&quot;</span>)</span></code></pre></div>
<p>While this code is a little more involved, let’s break it down piece by piece:</p>
<ul>
<li>To make things easier the variable <code>quantile_vals</code> computes the different quantiles, expressed between 0 to 1 - so 2.5% is 0.025, 50% is 0.5, and 97.5% is .975.</li>
<li>As above, we are still grouping by the variable <code>t</code> and summarizing our data frame.</li>
<li>However rather than applying the mean, we are using the command <code>quantile</code>, whose value is computed with the new column <code>q_val</code>. Like the mean, we define to which columns we apply the quantile function in the column <code>value</code>. We use <code>probs = quantile_vals</code> to specify the quantiles that we wish to compute.</li>
<li>We also create a new column called <code>q_name</code> the contains the names of the quantile probabilities.</li>
<li>The command <code>pivot_wider</code> takes the values in <code>q_val</code> with the associated names in <code>q_name</code> and creates new columns associated with each quantile. This process of making a data frame wider is the opposite of making a skinny and tall data frame with <code>pivot_longer</code>. A key convention with column names is not to start them with a number, so we <em>glue</em> a <code>q</code> onto the names of the column using the option <code>names_glue = "q{q_name}"</code>.</li>
</ul>
<p>Wow. This is getting involved. One thing to keep in mind is that the the code as written should be easily adaptable if you need to compute an ensemble average. If you take an introductory data science or data visualization course I bet you will learn more about the role of pivoting data - but for now you can just adapt the above code to your needs</p>
</div>
<div id="visualize" class="section level3 hasAnchor" number="22.2.4">
<h3><span class="header-section-number">22.2.4</span> Visualize<a href="stoch-sim-22.html#visualize" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To plot the 95% confidence interval we introduce the plot geom called <code>geom_ribbon</code>. Applying <code>geom_ribbon</code> requires a few more aesthetics (<code>ymin</code> and <code>ymax</code>, or the minimum and maximum <span class="math inline">\(y\)</span> values to be plotted). The option <code>alpha = 0.2</code> refers to the transparency of the plot. The <code>fill</code> aesthetic just provides the shading (in other words the fill) between <code>ymin</code> and <code>ymax</code>.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="stoch-sim-22.html#cb92-1" tabindex="-1"></a>logistic_quantile <span class="sc">%&gt;%</span></span>
<span id="cb92-2"><a href="stoch-sim-22.html#cb92-2" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb92-3"><a href="stoch-sim-22.html#cb92-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> q0<span class="fl">.5</span>), </span>
<span id="cb92-4"><a href="stoch-sim-22.html#cb92-4" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">inherit.aes =</span> <span class="cn">FALSE</span></span>
<span id="cb92-5"><a href="stoch-sim-22.html#cb92-5" tabindex="-1"></a>            ) <span class="sc">+</span></span>
<span id="cb92-6"><a href="stoch-sim-22.html#cb92-6" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">ymin =</span> q0<span class="fl">.025</span>, <span class="at">ymax =</span> q0<span class="fl">.975</span>),</span>
<span id="cb92-7"><a href="stoch-sim-22.html#cb92-7" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">&quot;red&quot;</span>, <span class="at">inherit.aes =</span> <span class="cn">FALSE</span></span>
<span id="cb92-8"><a href="stoch-sim-22.html#cb92-8" tabindex="-1"></a>              ) <span class="sc">+</span></span>
<span id="cb92-9"><a href="stoch-sim-22.html#cb92-9" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb92-10"><a href="stoch-sim-22.html#cb92-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Ensemble average&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:logistic-conf"></span>
<img src="explore-model-zobitz-220419_files/figure-html/logistic-conf-1.png" alt="Ensemble average plot for the logistic differential equation with 500 random initial conditions." width="672" />
<p class="caption">
FIGURE 22.5: Ensemble average plot for the logistic differential equation with 500 random initial conditions.
</p>
</div>
<p>Making ensemble averages isn’t easy and requires strengthening your computational skills on several levels. Fortunately there are a lot of good tools when doing iteration and looping that easily allow you to adapt (shall I say iterate on?) existing examples to your needs. In future chapters we will move beyond random initial conditions to figuring out how the variables or parameters can be subject to random effects as time goes on.</p>
</div>
</div>
<div id="exercises-21" class="section level2 hasAnchor" number="22.3">
<h2><span class="header-section-number">22.3</span> Exercises<a href="stoch-sim-22.html#exercises-21" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<!-- EXERCISES - how are the logistic results different with varying k? varying r? what would you expect? - do a stochastic lotka-volterra or something stable (predator-prey) - find an ensemble average plot and interpret it. - do random initial conditions with neutral stability problem (birfurcation). - what if they plotted the ensemble phase plane? HMMM - bonus problem. -->
<div class="exercise">
<p><span id="exr:unnamed-chunk-268" class="exercise"><strong>Exercise 22.1  </strong></span>Using the code to produce Figure <a href="stoch-sim-22.html#fig:logistic-conf">22.5</a>:</p>
<ol style="list-style-type: lower-alpha">
<li>Adjust the <code>alpha</code> level to a number between 0 and 1. What does that do to the plot?</li>
<li>Adjust the <code>fill</code> level to a color of your choosing. A list of R Colors can be found at the <a href="http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/">R Color chart</a>.</li>
</ol>
</div>
<div class="exercise">
<p><span id="exr:unnamed-chunk-269" class="exercise"><strong>Exercise 22.2  </strong></span>Read the Chapter 12 (tidy data) in <span class="citation">Wickham and Grolemund (<a href="#ref-wickham_r_2017">2017</a>)</span>. In this chapter you will learn about tidy data. Explain what tidy data is and the potential uses for pivoting data wider or longer.</p>
</div>
<div class="exercise">
<p><span id="exr:unnamed-chunk-270" class="exercise"><strong>Exercise 22.3  </strong></span>Look at the documentation for quantile (remember you can type <code>?quantile</code> at the command line to see the associated help for this function). Change the ensemble average in <code>quantile_vals</code> to compute the 25%, 50%, and 75% percentile for <code>logistic_sim</code>. Finally, produce a ensemble average plot of this percentile.</p>
</div>
<div class="exercise">
<p><span id="exr:unnamed-chunk-271" class="exercise"><strong>Exercise 22.4  </strong></span>Consider the logistic differential equation: <span class="math inline">\(\displaystyle \frac{dx}{dt} = rx\left(1- \frac{x}{K}\right)\)</span>. The function <code>logistic_mod</code> below takes the initial value problem <span class="math inline">\(x(0)=3\)</span> and solves the differential equation.</p>
<ol style="list-style-type: lower-alpha">
<li>Run <code>logistic_mod(r=0.8,K=100)</code> and plot its result.</li>
<li>Run 500 simulations with varying <span class="math inline">\(r\)</span> chosen from a uniform distribution with minimum value of 0.4 and maximum value of 1.0. Create a spaghetti and ensemble average plot. Set <span class="math inline">\(K=100\)</span>.</li>
<li>Run 500 simulations with varying <span class="math inline">\(K\)</span> chosen from a uniform distribution with minimum value of 50 and maximum value of 150. Create a spaghetti and ensemble average plot. Set <span class="math inline">\(r=0.8\)</span>.</li>
<li>Compare your results along with Figures <a href="stoch-sim-22.html#fig:logistic-example-many">22.4</a> and <a href="stoch-sim-22.html#fig:logistic-conf">22.5</a>. How does randomizing the initial condition or the parameters affect the results?</li>
</ol>
</div>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="stoch-sim-22.html#cb93-1" tabindex="-1"></a>logistic_mod <span class="ot">&lt;-</span> <span class="cf">function</span>(r,K) {</span>
<span id="cb93-2"><a href="stoch-sim-22.html#cb93-2" tabindex="-1"></a>  logistic_eq <span class="ot">&lt;-</span> <span class="fu">c</span>(dx <span class="sc">~</span> r <span class="sc">*</span> x <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> x <span class="sc">/</span> K)) <span class="co"># Define the rate equation</span></span>
<span id="cb93-3"><a href="stoch-sim-22.html#cb93-3" tabindex="-1"></a>  </span>
<span id="cb93-4"><a href="stoch-sim-22.html#cb93-4" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">r=</span>r,<span class="at">K=</span>K) <span class="co"># Identify any parameters</span></span>
<span id="cb93-5"><a href="stoch-sim-22.html#cb93-5" tabindex="-1"></a>  </span>
<span id="cb93-6"><a href="stoch-sim-22.html#cb93-6" tabindex="-1"></a>  init_cond <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">x =</span> <span class="dv">3</span>) <span class="co"># Initial condition</span></span>
<span id="cb93-7"><a href="stoch-sim-22.html#cb93-7" tabindex="-1"></a>  soln <span class="ot">&lt;-</span> <span class="fu">euler</span>(</span>
<span id="cb93-8"><a href="stoch-sim-22.html#cb93-8" tabindex="-1"></a>    <span class="at">system_eq =</span> logistic_eq,</span>
<span id="cb93-9"><a href="stoch-sim-22.html#cb93-9" tabindex="-1"></a>    <span class="at">initial_condition =</span> init_cond,</span>
<span id="cb93-10"><a href="stoch-sim-22.html#cb93-10" tabindex="-1"></a>    <span class="at">parameters =</span> params,</span>
<span id="cb93-11"><a href="stoch-sim-22.html#cb93-11" tabindex="-1"></a>    <span class="at">deltaT =</span> .<span class="dv">05</span>,</span>
<span id="cb93-12"><a href="stoch-sim-22.html#cb93-12" tabindex="-1"></a>    <span class="at">n_steps =</span> <span class="dv">200</span></span>
<span id="cb93-13"><a href="stoch-sim-22.html#cb93-13" tabindex="-1"></a>  )</span>
<span id="cb93-14"><a href="stoch-sim-22.html#cb93-14" tabindex="-1"></a>  </span>
<span id="cb93-15"><a href="stoch-sim-22.html#cb93-15" tabindex="-1"></a>  <span class="fu">return</span>(soln)</span>
<span id="cb93-16"><a href="stoch-sim-22.html#cb93-16" tabindex="-1"></a>}</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unnamed-chunk-273" class="exercise"><strong>Exercise 22.5  </strong></span>Using the data frame <code>my_table</code>, compare the following code below. The data frame <code>table1</code> is skinny and long, and the second data frame <code>table2</code> is called short and wide. Why did we need to make this data frame short and wide for plotting?</p>
</div>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="stoch-sim-22.html#cb94-1" tabindex="-1"></a><span class="co"># First code chunk</span></span>
<span id="cb94-2"><a href="stoch-sim-22.html#cb94-2" tabindex="-1"></a>table1 <span class="ot">&lt;-</span> my_table <span class="sc">%&gt;%</span></span>
<span id="cb94-3"><a href="stoch-sim-22.html#cb94-3" tabindex="-1"></a>  <span class="fu">rowwise</span>(t) <span class="sc">%&gt;%</span></span>
<span id="cb94-4"><a href="stoch-sim-22.html#cb94-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">q_val =</span> <span class="fu">quantile</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;sim&quot;</span>)),</span>
<span id="cb94-5"><a href="stoch-sim-22.html#cb94-5" tabindex="-1"></a>                                <span class="at">probs =</span> quantile_vals),</span>
<span id="cb94-6"><a href="stoch-sim-22.html#cb94-6" tabindex="-1"></a>            <span class="at">q_name =</span> quantile_vals)</span>
<span id="cb94-7"><a href="stoch-sim-22.html#cb94-7" tabindex="-1"></a></span>
<span id="cb94-8"><a href="stoch-sim-22.html#cb94-8" tabindex="-1"></a><span class="co"># Second code chunk</span></span>
<span id="cb94-9"><a href="stoch-sim-22.html#cb94-9" tabindex="-1"></a>table2 <span class="ot">&lt;-</span> my_table <span class="sc">%&gt;%</span></span>
<span id="cb94-10"><a href="stoch-sim-22.html#cb94-10" tabindex="-1"></a>  <span class="fu">rowwise</span>(t) <span class="sc">%&gt;%</span></span>
<span id="cb94-11"><a href="stoch-sim-22.html#cb94-11" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">q_val =</span> <span class="fu">quantile</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;sim&quot;</span>)),</span>
<span id="cb94-12"><a href="stoch-sim-22.html#cb94-12" tabindex="-1"></a>                                <span class="at">probs =</span> quantile_vals),</span>
<span id="cb94-13"><a href="stoch-sim-22.html#cb94-13" tabindex="-1"></a>            <span class="at">q_name =</span> quantile_vals) <span class="sc">%&gt;%</span></span>
<span id="cb94-14"><a href="stoch-sim-22.html#cb94-14" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">&quot;q_name&quot;</span>,<span class="at">values_from=</span><span class="st">&quot;q_val&quot;</span>,</span>
<span id="cb94-15"><a href="stoch-sim-22.html#cb94-15" tabindex="-1"></a>              <span class="at">names_glue =</span> <span class="st">&quot;q{q_name}&quot;</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unnamed-chunk-274" class="exercise"><strong>Exercise 22.6  </strong></span>Consider the following differential equation:</p>
<p><span class="math display">\[\begin{equation}
\begin{split}
\frac{dx}{dt} =-y-x(x^2+y^2-1) \\
\frac{dy}{dt}=x-y(x^2+y^2-1)
\end{split}
\end{equation}\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Generate a phase plane for this differential equation. Store this phase plane in a variable called <code>pp1</code>. Set your x and y windows to be between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span>.</li>
<li>The code below defines a function <code>limit_cycle_mod</code> that creates a solution trajectory of the differential equation. Super-impose a few different solution trajectories with random initial conditions onto your phase plane (<code>pp1</code>). Use initial conditions <code>x0</code> and <code>y0</code> between 0 and 1. Be sure to use the plot geom <code>geom_path</code>.</li>
<li>Modify the code from this chapter to run 50 different simulations with random initial conditions <code>x0</code> and <code>y0</code> between 0 and 1. <em>Note:</em> It may be helpful to include the code <code>map(~ limit_cycle_mod(runif(1),runif(1)))</code>.</li>
<li>Plot the initial conditions from your simulation onto your phase plane. Isn’t the result pretty?</li>
</ol>
</div>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="stoch-sim-22.html#cb95-1" tabindex="-1"></a>limit_cycle_mod <span class="ot">&lt;-</span> <span class="cf">function</span>(x0,y0) {</span>
<span id="cb95-2"><a href="stoch-sim-22.html#cb95-2" tabindex="-1"></a>  limit_cycle_eq <span class="ot">&lt;-</span> <span class="fu">c</span>(dx <span class="sc">~</span> <span class="sc">-</span>y<span class="sc">-</span>x<span class="sc">*</span>x<span class="sc">*</span>(x<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span>y<span class="sc">^</span><span class="dv">2-1</span>),</span>
<span id="cb95-3"><a href="stoch-sim-22.html#cb95-3" tabindex="-1"></a>                   dy <span class="sc">~</span> x<span class="sc">-</span>y<span class="sc">*</span>(x<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span>y<span class="sc">^</span><span class="dv">2-1</span>) ) <span class="co"># Define the rate equation</span></span>
<span id="cb95-4"><a href="stoch-sim-22.html#cb95-4" tabindex="-1"></a></span>
<span id="cb95-5"><a href="stoch-sim-22.html#cb95-5" tabindex="-1"></a>  init_cond <span class="ot">=</span> <span class="fu">c</span>(<span class="at">x=</span>x0,<span class="at">y=</span>y0)</span>
<span id="cb95-6"><a href="stoch-sim-22.html#cb95-6" tabindex="-1"></a>  soln <span class="ot">&lt;-</span> <span class="fu">rk4</span>(</span>
<span id="cb95-7"><a href="stoch-sim-22.html#cb95-7" tabindex="-1"></a>    <span class="at">system_eq =</span> limit_cycle_eq,</span>
<span id="cb95-8"><a href="stoch-sim-22.html#cb95-8" tabindex="-1"></a>    <span class="at">initial_condition =</span> init_cond,</span>
<span id="cb95-9"><a href="stoch-sim-22.html#cb95-9" tabindex="-1"></a>    <span class="at">deltaT =</span> .<span class="dv">05</span>,</span>
<span id="cb95-10"><a href="stoch-sim-22.html#cb95-10" tabindex="-1"></a>    <span class="at">n_steps =</span> <span class="dv">200</span></span>
<span id="cb95-11"><a href="stoch-sim-22.html#cb95-11" tabindex="-1"></a>  )</span>
<span id="cb95-12"><a href="stoch-sim-22.html#cb95-12" tabindex="-1"></a>  </span>
<span id="cb95-13"><a href="stoch-sim-22.html#cb95-13" tabindex="-1"></a>  <span class="fu">return</span>(soln)</span>
<span id="cb95-14"><a href="stoch-sim-22.html#cb95-14" tabindex="-1"></a>}</span></code></pre></div>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-finnish_meteorological_institute_weather_2021" class="csl-entry">
Finnish Meteorological Institute. 2021. <span>“Weather in <span>Kuopio</span>.”</span> https://en.ilmatieteenlaitos.fi/weather/kuopio.
</div>
<div id="ref-wickham_r_2017" class="csl-entry">
Wickham, Hadley, and Garrett Grolemund. 2017. <em>R for <span>Data Science</span>: <span>Import</span>, <span>Tidy</span>, <span>Transform</span>, <span>Visualize</span>, and <span>Model Data</span></em>. 1st edition. <span>Sebastopol, CA</span>: <span>O’Reilly Media</span>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="45">
<li id="fn45"><p>While I could have picked any city, a lot of this textbook was written while I was on sabbatical in Kuopio. I highly recommend Finland as a country to visit.<a href="stoch-sim-22.html#fnref45" class="footnote-back">↩︎</a></p></li>
<li id="fn46"><p>Notice the meteorologist’s temperature forecast on Wednesday, December 22 - sometimes what they predict may diverge from the model outcomes!<a href="stoch-sim-22.html#fnref46" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="stoch-sys-21.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="random-walks-23.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jules32/bookdown-tutorial/edit/master/22-stochasticSimulation.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://jmzobitz.github.io/ModelingWithR/22-stochasticSimulation.Rmd",
"text": null
},
"download": {},
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
